<center><h1>Netflix Prize</h1></center>

In [1]:
from src import *
import src
import numpy as np
from importlib import reload
import pandas as pd
reload(src)
import matplotlib.pyplot as plt
from math import sqrt

import warnings
warnings.filterwarnings('ignore')

## Pré-processamento

In [22]:
def df_to_latex(df, legenda):
    latex = r'''\begin{table}[]
                \centering
                        '''
    latex = latex + df.to_latex(index=False, header=True, 
                                column_format='c'*len(df.columns.to_list()))
    latex = latex + r'''
                    \caption{%s}
                    \end{table}
                        ''' % legenda 
    return latex

### Carregamento

In [2]:
n = pd.read_csv('data/raw/netflix/movie_titles.csv', 
                names = ['movieId', 'year', 'name'], 
                encoding='ISO-8859-1',
               lineterminator='\n',
               usecols=range(3))[['movieId', 'name']]

In [3]:
n

       movieId                                               name
0            1                                    Dinosaur Planet
1            2                         Isle of Man TT 2004 Review
2            3                                          Character
3            4                       Paula Abdul's Get Up & Dance
4            5                           The Rise and Fall of ECW
...        ...                                                ...
17765    17766  Where the Wild Things Are and Other Maurice Se...
17766    17767                  Fidel Castro: American Experience
17767    17768                                              Epoch
17768    17769                                        The Company
17769    17770                                       Alien Hunter

[17770 rows x 2 columns]

In [4]:
n_g = pd.read_csv('data/raw/netflix/netflix_genres.csv')

In [21]:
n_g

       movieId                            genres
0            1      Documentary|Animation|Family
1            3               Crime|Drama|Mystery
2            4                            Family
3            5                 Documentary|Sport
4            6                       Documentary
...        ...                               ...
12274    17764      Comedy|Drama|History|Romance
12275    17765    Action|Adventure|Family|Sci-Fi
12276    17768              Action|Drama|Fantasy
12277    17769               Drama|Music|Romance
12278    17770  Action|Adventure|Sci-Fi|Thriller

[12279 rows x 2 columns]

In [5]:
n_g_found = n_g['movieId'].to_list()

In [6]:
n[~n['movieId'].isin(n_g_found)]

       movieId                                               name
1            2                         Isle of Man TT 2004 Review
9           10                                            Fighter
10          11                     Full Frame: Documentary Shorts
12          13  Lord of the Rings: The Return of the King: Ext...
13          14                                 Nature: Antarctica
...        ...                                                ...
17749    17750                     The Hee Haw Collection: Vol. 4
17750    17751                               Highlander: Season 2
17756    17757  Ulysses S. Grant: Warrior / President: America...
17765    17766  Where the Wild Things Are and Other Maurice Se...
17766    17767                  Fidel Castro: American Experience

[5491 rows x 2 columns]

In [28]:
n_g['g'] = n_g['genres'].str.split('|')

In [31]:
n_g.explode('g')['g'].nunique()

27

In [23]:
print(df_to_latex(n_g.head(), 'Primeiras 5 linhas do conjunto de metadados de filmes presentes no conjunto de dados Netflix Prize com os gêneros obtidos pelo cruzamento com o conjunto IMDb'))

\begin{table}[]
                \centering
                        \begin{tabular}{cc}
\toprule
movieId & genres \\
\midrule
1 & Documentary|Animation|Family \\
3 & Crime|Drama|Mystery \\
4 & Family \\
5 & Documentary|Sport \\
6 & Documentary \\
\bottomrule
\end{tabular}

                    \caption{Primeiras 5 linhas do conjunto de metadados de filmes presentes no conjunto de dados Netflix Prize com os gêneros obtidos pelo cruzamento com o conjunto IMDb}
                    \end{table}

## Experimentos

In [2]:
userColumn='userId'
itemColumn='artistId'
ratingColumn='rating'

In [3]:
loader = DataLoader(file_path='data/processed/yahoo_music/yahoo_music_tratado.csv',
                    separator=',',
                    header=['userId', 'artistId', 'rating'],
                    genre_data_path='data/processed/yahoo_music/yahoo_music_artists_metadata_with_genres.csv',
                    genre_data_separator=',',
                    genre_data_header=['artistId', 'artistName', 'genres'],
                    genre_item_column='artistId',
                    genre_genre_column='genres',
                    genre_genre_separator='|',
                    genre_data_encoding='ISO-8859-1'
                    )

24/09/06 21:24:53 WARN Utils: Your hostname, david-Nitro resolves to a loopback address: 127.0.1.1; using 192.168.15.14 instead (on interface wlp9s0)
24/09/06 21:24:53 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
24/09/06 21:24:53 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [4]:
df = loader.load_data()
df_pandas = loader.convert_to_pandas(df)
genres_map = loader.get_genre_map()
# (train, test) = loader.train_test_separator(df)

In [5]:
df_pandas

         userId  artistId  rating
0         12722   1000276     5.0
1         12722   1000335     5.0
2         12722   1000418     5.0
3         12722   1000454     5.0
4         12722   1000656     5.0
...         ...       ...     ...
112518  1942234   1097451     5.0
112519  1942234   1098966     5.0
112520  1942234   1099341     5.0
112521  1942234   1099448     5.0
112522  1942234   1099524     5.0

[112523 rows x 3 columns]

## ALS

In [6]:
kfold = KFOLD(df_pandas, 'FC', userColumn, itemColumn, ratingColumn, genres_map)

24/09/06 21:25:00 WARN SparkSession: Using an existing Spark session; only runtime SQL configurations will take effect.

In [ ]:
results = kfold.run_cross_validation()

1) Running FC
******************************
Lambda = 0.0
Reseting metrics lists
********************
FAIRNESS MEASURE: kullback-leibler
=====1º Fold=====
Train/test spliting
Instantiating ALS...

24/09/06 21:25:05 WARN SparkSession: Using an existing Spark session; only runtime SQL configurations will take effect.
24/09/06 21:25:08 WARN InstanceBuilder: Failed to load implementation from:dev.ludovic.netlib.blas.VectorBLAS
24/09/06 21:25:11 WARN GarbageCollectionMetrics: To enable non-built-in garbage collector(s) List(G1 Concurrent GC), users should configure it(them) to spark.eventLog.gcMetrics.youngGenerationGarbageCollectors or spark.eventLog.gcMetrics.oldGenerationGarbageCollectors

Getting n = 100 predictions for each user

Calibrating...
CALCULATING MRMC
MRMC = 0.3252801252573285
CALCULATING MACE
MACE = 0.001991729290430589
CALCULATING MAP
MAP = 0.008682745825602968
CALCULATING MRR
MRR = 0.008682745825602968
=====2º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.3712320246142023
CALCULATING MACE
MACE = 0.0021874243253553606
CALCULATING MAP
MAP = 0.003116883116883117
CALCULATING MRR
MRR = 0.003116883116883117
=====3º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.29430458612782917
CALCULATING MACE
MACE = 0.0013401230803828216
CALCULATING MAP
MAP = 0.0014285714285714288
CALCULATING MRR
MRR = 0.0014285714285714288
=====4º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.3751154443408931
CALCULATING MACE
MACE = 0.0022264550264550266
CALCULATING MAP
MAP = 0.0
CALCULATING MRR
MRR = 0.0
=====5º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.41822480247494465
CALCULATING MACE
MACE = 0.0016331393474250616
CALCULATING MAP
MAP = 0.001280148423005566
CALCULATING MRR
MRR = 0.001280148423005566
===============
Getting mean and stdev
MACE Mean = 0.001875774214009772
MACE Error = 0.0003805726669458661
MRMC Mean = 0.3568313965630395
MRMC Error = 0.04799979042944361
MAP Mean = 0.002901669758812616
MAP Error = 0.0034163648371387644
MRR Mean = 0.002901669758812616
MRR Error = 0.0034163648371387644
Appending to results


Reseting metrics lists
********************
FAIRNESS MEASURE: hellinger
=====1º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.659498800259692
CALCULATING MACE
MACE = 0.001991729290430589
CALCULATING MAP
MAP = 0.008682745825602968
CALCULATING MRR
MRR = 0.008682745825602968
=====2º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.7182581591421316
CALCULATING MACE
MACE = 0.0021874243253553606
CALCULATING MAP
MAP = 0.003116883116883117
CALCULATING MRR
MRR = 0.003116883116883117
=====3º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.6856933183882559
CALCULATING MACE
MACE = 0.0013401230803828216
CALCULATING MAP
MAP = 0.0014285714285714288
CALCULATING MRR
MRR = 0.0014285714285714288
=====4º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.6999558269239525
CALCULATING MACE
MACE = 0.0022264550264550266
CALCULATING MAP
MAP = 0.0
CALCULATING MRR
MRR = 0.0
=====5º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.7612075831147964
CALCULATING MACE
MACE = 0.0016331393474250616
CALCULATING MAP
MAP = 0.001280148423005566
CALCULATING MRR
MRR = 0.001280148423005566
===============
Getting mean and stdev
MACE Mean = 0.001875774214009772
MACE Error = 0.0003805726669458661
MRMC Mean = 0.7049227375657656
MRMC Error = 0.03809065551651712
MAP Mean = 0.002901669758812616
MAP Error = 0.0034163648371387644
MRR Mean = 0.002901669758812616
MRR Error = 0.0034163648371387644
Appending to results


Reseting metrics lists
********************
FAIRNESS MEASURE: pearson
=====1º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user

Calibrating...
CALCULATING MRMC
MRMC = 0.36147048798950404
CALCULATING MACE
MACE = 0.001991729290430589
CALCULATING MAP
MAP = 0.008682745825602968
CALCULATING MRR
MRR = 0.008682745825602968
=====2º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.3939398400243541
CALCULATING MACE
MACE = 0.0021874243253553606
CALCULATING MAP
MAP = 0.003116883116883117
CALCULATING MRR
MRR = 0.003116883116883117
=====3º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.2655579094505297
CALCULATING MACE
MACE = 0.0013401230803828216
CALCULATING MAP
MAP = 0.0014285714285714288
CALCULATING MRR
MRR = 0.0014285714285714288
=====4º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.42231065541011453
CALCULATING MACE
MACE = 0.0022264550264550266
CALCULATING MAP
MAP = 0.0
CALCULATING MRR
MRR = 0.0
=====5º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.45291585730014705
CALCULATING MACE
MACE = 0.0016331393474250616
CALCULATING MAP
MAP = 0.001280148423005566
CALCULATING MRR
MRR = 0.001280148423005566
===============
Getting mean and stdev
MACE Mean = 0.001875774214009772
MACE Error = 0.0003805726669458661
MRMC Mean = 0.3792389500349299
MRMC Error = 0.07200463850750702
MAP Mean = 0.002901669758812616
MAP Error = 0.0034163648371387644
MRR Mean = 0.002901669758812616
MRR Error = 0.0034163648371387644
Appending to results


******************************
Lambda = 0.1
Reseting metrics lists
********************
FAIRNESS MEASURE: kullback-leibler
=====1º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user

Calibrating...
CALCULATING MRMC
MRMC = 0.11332756633825354
CALCULATING MACE
MACE = 0.0012193520764949323
CALCULATING MAP
MAP = 0.004862914862914863
CALCULATING MRR
MRR = 0.004862914862914863
=====2º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user

Calibrating...
CALCULATING MRMC
MRMC = 0.12509547334614296
CALCULATING MACE
MACE = 0.0010055122764482361
CALCULATING MAP
MAP = 0.0028571428571428576
CALCULATING MRR
MRR = 0.0028571428571428576
=====3º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.1273634778879431
CALCULATING MACE
MACE = 0.000703240962981223
CALCULATING MAP
MAP = 0.0011327561327561329
CALCULATING MRR
MRR = 0.0011327561327561329
=====4º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.12066198195781472
CALCULATING MACE
MACE = 0.0007875394446823017
CALCULATING MAP
MAP = 0.003896103896103896
CALCULATING MRR
MRR = 0.0047619047619047615
=====5º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.11481539217771888
CALCULATING MACE
MACE = 0.0009040050858232669
CALCULATING MAP
MAP = 0.005245310245310245
CALCULATING MRR
MRR = 0.005245310245310245
===============
Getting mean and stdev
MACE Mean = 0.000923929969285992
MACE Error = 0.00020101797678077497
MRMC Mean = 0.12025277834157463
MRMC Error = 0.006158427561711113
MAP Mean = 0.003598845598845599
MAP Error = 0.0016604818309393103
MRR Mean = 0.0037720057720057715
MRR Error = 0.0017423562736393013
Appending to results


Reseting metrics lists
********************
FAIRNESS MEASURE: hellinger
=====1º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user

Calibrating...
CALCULATING MRMC
MRMC = 0.42049545075045364
CALCULATING MACE
MACE = 0.0009944024229738507
CALCULATING MAP
MAP = 0.003823953823953824
CALCULATING MRR
MRR = 0.003823953823953824
=====2º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.42101093642414256
CALCULATING MACE
MACE = 0.0005825434952170288
CALCULATING MAP
MAP = 0.003463203463203463
CALCULATING MRR
MRR = 0.003463203463203463
=====3º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.46350693268707577
CALCULATING MACE
MACE = 0.0006917844060701205
CALCULATING MAP
MAP = 0.0019109461966604826
CALCULATING MRR
MRR = 0.0019109461966604826
=====4º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.41779675831286955
CALCULATING MACE
MACE = 0.0006131363585909037
CALCULATING MAP
MAP = 0.0021645021645021645
CALCULATING MRR
MRR = 0.0021645021645021645
=====5º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.43518873076647824
CALCULATING MACE
MACE = 0.0006217563100679981
CALCULATING MAP
MAP = 0.007012987012987013
CALCULATING MRR
MRR = 0.007012987012987013
===============
Getting mean and stdev
MACE Mean = 0.0007007245985839804
MACE Error = 0.00016896823307193775
MRMC Mean = 0.4315997617882039
MRMC Error = 0.019084680402423657
MAP Mean = 0.0036751185322613893
MAP Error = 0.0020373200396237587
MRR Mean = 0.0036751185322613893
MRR Error = 0.0020373200396237587
Appending to results


Reseting metrics lists
********************
FAIRNESS MEASURE: pearson
=====1º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.05068857960617096
CALCULATING MACE
MACE = 0.001327321067580807
CALCULATING MAP
MAP = 0.003231292517006802
CALCULATING MRR
MRR = 0.003231292517006802
=====2º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.09716409155003373
CALCULATING MACE
MACE = 0.0015072469949317245
CALCULATING MAP
MAP = 0.0025974025974025974
CALCULATING MRR
MRR = 0.0025974025974025974
=====3º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.05592293234775021
CALCULATING MACE
MACE = 0.0009233976827961799
CALCULATING MAP
MAP = 0.0019264069264069265
CALCULATING MRR
MRR = 0.0019264069264069265
=====4º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.08198114445868868
CALCULATING MACE
MACE = 0.0011261336093309072
CALCULATING MAP
MAP = 0.00487012987012987
CALCULATING MRR
MRR = 0.00487012987012987
=====5º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.05139572333008908
CALCULATING MACE
MACE = 0.0011970436085268629
CALCULATING MAP
MAP = 0.004880437023294166
CALCULATING MRR
MRR = 0.004880437023294166
===============
Getting mean and stdev
MACE Mean = 0.0012162285926332964
MACE Error = 0.000218671191434622
MRMC Mean = 0.06743049425854654
MRMC Error = 0.02100974651932749
MAP Mean = 0.003501133786848072
MAP Error = 0.001336594249650252
MRR Mean = 0.003501133786848072
MRR Error = 0.001336594249650252
Appending to results


******************************
Lambda = 0.2
Reseting metrics lists
********************
FAIRNESS MEASURE: kullback-leibler
=====1º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.11244956750600828
CALCULATING MACE
MACE = 0.0012026011506530976
CALCULATING MAP
MAP = 0.005483405483405483
CALCULATING MRR
MRR = 0.005483405483405483
=====2º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.12503078939550302
CALCULATING MACE
MACE = 0.0010055122764482361
CALCULATING MAP
MAP = 0.0028571428571428576
CALCULATING MRR
MRR = 0.0028571428571428576
=====3º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.1273549635271037
CALCULATING MACE
MACE = 0.0007013856754116498
CALCULATING MAP
MAP = 0.0013924963924963928
CALCULATING MRR
MRR = 0.0013924963924963928
=====4º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.12026115792116758
CALCULATING MACE
MACE = 0.0007658217005810585
CALCULATING MAP
MAP = 0.004502164502164502
CALCULATING MRR
MRR = 0.005281385281385281
=====5º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.11456170648885448
CALCULATING MACE
MACE = 0.0009821563717667607
CALCULATING MAP
MAP = 0.005353535353535353
CALCULATING MRR
MRR = 0.005353535353535353
===============
Getting mean and stdev
MACE Mean = 0.0009314954349721606
MACE Error = 0.00020120985321671225
MRMC Mean = 0.11993163696772742
MRMC Error = 0.006442694186547777
MAP Mean = 0.003917748917748918
MAP Error = 0.0017575615407552732
MRR Mean = 0.004073593073593074
MRR Error = 0.0018542259726458574
Appending to results


Reseting metrics lists
********************
FAIRNESS MEASURE: hellinger
=====1º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.4208041459746242
CALCULATING MACE
MACE = 0.000994246734506474
CALCULATING MAP
MAP = 0.005916305916305916
CALCULATING MRR
MRR = 0.005916305916305916
=====2º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.4209832999518919
CALCULATING MACE
MACE = 0.0005825434952170288
CALCULATING MAP
MAP = 0.003463203463203463
CALCULATING MRR
MRR = 0.003463203463203463
=====3º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.46452499314953816
CALCULATING MACE
MACE = 0.0006917844060701205
CALCULATING MAP
MAP = 0.0019109461966604826
CALCULATING MRR
MRR = 0.0019109461966604826
=====4º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.4123020601868088
CALCULATING MACE
MACE = 0.000585341930796476
CALCULATING MAP
MAP = 0.0021645021645021645
CALCULATING MRR
MRR = 0.0021645021645021645
=====5º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.43502935726850617
CALCULATING MACE
MACE = 0.0005964641419186872
CALCULATING MAP
MAP = 0.007272727272727272
CALCULATING MRR
MRR = 0.007272727272727272
===============
Getting mean and stdev
MACE Mean = 0.0006900761417017573
MACE Error = 0.0001759391934672829
MRMC Mean = 0.43072877130627385
MRMC Error = 0.020577267390682632
MAP Mean = 0.004145537002679859
MAP Error = 0.00236105991506241
MRR Mean = 0.004145537002679859
MRR Error = 0.00236105991506241
Appending to results


Reseting metrics lists
********************
FAIRNESS MEASURE: pearson
=====1º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.05066872855870973
CALCULATING MACE
MACE = 0.0013115167660622193
CALCULATING MAP
MAP = 0.0036641929499072355
CALCULATING MRR
MRR = 0.0036641929499072355
=====2º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.09716367602383952
CALCULATING MACE
MACE = 0.0015072469949317245
CALCULATING MAP
MAP = 0.0025974025974025974
CALCULATING MRR
MRR = 0.0025974025974025974
=====3º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.05592175785172364
CALCULATING MACE
MACE = 0.0009233976827961799
CALCULATING MAP
MAP = 0.0019264069264069265
CALCULATING MRR
MRR = 0.0019264069264069265
=====4º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.08198185615191624
CALCULATING MACE
MACE = 0.0011274529249359366
CALCULATING MAP
MAP = 0.00487012987012987
CALCULATING MRR
MRR = 0.00487012987012987
=====5º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.0513841430903178
CALCULATING MACE
MACE = 0.0011970436085268629
CALCULATING MAP
MAP = 0.004880437023294166
CALCULATING MRR
MRR = 0.004880437023294166
===============
Getting mean and stdev
MACE Mean = 0.0012133315954505845
MACE Error = 0.00021663835536134678
MRMC Mean = 0.06742403233530139
MRMC Error = 0.021016048694566584
MAP Mean = 0.003587713873428159
MAP Error = 0.0013287428434030613
MRR Mean = 0.003587713873428159
MRR Error = 0.0013287428434030613
Appending to results


******************************
Lambda = 0.30000000000000004
Reseting metrics lists
********************
FAIRNESS MEASURE: kullback-leibler
=====1º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.11219178839823563
CALCULATING MACE
MACE = 0.0011883931364450834
CALCULATING MAP
MAP = 0.005194805194805195
CALCULATING MRR
MRR = 0.005194805194805195
=====2º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.12502891798705337
CALCULATING MACE
MACE = 0.0010167996903330525
CALCULATING MAP
MAP = 0.0028571428571428576
CALCULATING MRR
MRR = 0.0028571428571428576
=====3º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.1273302589030149
CALCULATING MACE
MACE = 0.0007115183998300885
CALCULATING MAP
MAP = 0.0014213564213564215
CALCULATING MRR
MRR = 0.0014213564213564215
=====4º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.12003180391481685
CALCULATING MACE
MACE = 0.0008103148313674633
CALCULATING MAP
MAP = 0.004502164502164502
CALCULATING MRR
MRR = 0.005281385281385281
=====5º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.11446868210277399
CALCULATING MACE
MACE = 0.0009821563717667607
CALCULATING MAP
MAP = 0.005353535353535353
CALCULATING MRR
MRR = 0.005353535353535353
===============
Getting mean and stdev
MACE Mean = 0.0009418364859484895
MACE Error = 0.0001859971260027112
MRMC Mean = 0.11981029026117893
MRMC Error = 0.006527009659250905
MAP Mean = 0.0038658008658008654
MAP Error = 0.0016865100585675469
MRR Mean = 0.004021645021645022
MRR Error = 0.0017926759513366933
Appending to results


Reseting metrics lists
********************
FAIRNESS MEASURE: hellinger
=====1º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.4223025407523936
CALCULATING MACE
MACE = 0.000994246734506474
CALCULATING MAP
MAP = 0.0058874458874458874
CALCULATING MRR
MRR = 0.0058874458874458874
=====2º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.42106472579004095
CALCULATING MACE
MACE = 0.0005825434952170288
CALCULATING MAP
MAP = 0.003463203463203463
CALCULATING MRR
MRR = 0.003463203463203463
=====3º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.46503223997826615
CALCULATING MACE
MACE = 0.0006917844060701205
CALCULATING MAP
MAP = 0.0019109461966604826
CALCULATING MRR
MRR = 0.0019109461966604826
=====4º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.4098629562392576
CALCULATING MACE
MACE = 0.000585341930796476
CALCULATING MAP
MAP = 0.0024242424242424242
CALCULATING MRR
MRR = 0.0024242424242424242
=====5º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.43634010355032765
CALCULATING MACE
MACE = 0.0006318731773277228
CALCULATING MAP
MAP = 0.007272727272727272
CALCULATING MRR
MRR = 0.007272727272727272
===============
Getting mean and stdev
MACE Mean = 0.0006971579487835644
MACE Error = 0.0001718953299194687
MRMC Mean = 0.43092051326205716
MRMC Error = 0.021259166041341822
MAP Mean = 0.004191713048855906
MAP Error = 0.002303515496306819
MRR Mean = 0.004191713048855906
MRR Error = 0.002303515496306819
Appending to results


Reseting metrics lists
********************
FAIRNESS MEASURE: pearson
=====1º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.05066533210633375
CALCULATING MACE
MACE = 0.0013115167660622193
CALCULATING MAP
MAP = 0.003923933209647496
CALCULATING MRR
MRR = 0.003923933209647496
=====2º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.0971632781954005
CALCULATING MACE
MACE = 0.0015072469949317245
CALCULATING MAP
MAP = 0.0025974025974025974
CALCULATING MRR
MRR = 0.0025974025974025974
=====3º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.05591985738917001
CALCULATING MACE
MACE = 0.0009233976827961799
CALCULATING MAP
MAP = 0.0019264069264069265
CALCULATING MRR
MRR = 0.0019264069264069265
=====4º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...
CALCULATING MRMC
MRMC = 0.08198150290361932
CALCULATING MACE
MACE = 0.0011274529249359366
CALCULATING MAP
MAP = 0.004545454545454545
CALCULATING MRR
MRR = 0.004545454545454545
=====5º Fold=====
Train/test spliting
Instantiating ALS...
Getting n = 100 predictions for each user
Calibrating...

In [ ]:
results

In [ ]:
results.to_csv('results/yahoo_movies/results_yahoo_movies2.csv', index=False)

In [ ]:
# results = pd.read_csv('results/yahoo_movies/results_yahoo_movies2.csv')

In [ ]:
#results.to_csv('results/yahoo_movies/results_yahoo_movies.csv', index=False)

In [ ]:
tradeoff_weights = results['Lambda'].drop_duplicates().to_list()
mrmc_kl = results[(results['FairnessMeasure'] == 'kullback-leibler') & (results['Statistic'] == 'mean')]['MAP'].to_list()
mrmc_he = results[(results['FairnessMeasure'] == 'hellinger') & (results['Statistic'] == 'mean')]['MAP'].to_list()
mrmc_pe = results[(results['FairnessMeasure'] == 'pearson') & (results['Statistic'] == 'mean')]['MAP'].to_list()

# Plotando o gráfico
plt.figure(figsize=(10, 6))
plt.plot(tradeoff_weights, mrmc_kl, marker='o', linestyle='-', color='b', label='Kullback-Leibler')
plt.plot(tradeoff_weights, mrmc_he, marker='s', linestyle='-', color='r', label='Hellinger')
plt.plot(tradeoff_weights, mrmc_pe, marker='^', linestyle='-', color='g', label='Pearson chi-quadrado')

plt.xlabel('λ')
plt.xticks(np.arange(0.0, 1.1, 0.1))
plt.ylabel('Mean rank miscalibration (MRMC)')
plt.title('MovieLens com ALS')
plt.legend()
plt.grid(True)
plt.show()

#### CRIANDO GRÁFICOS

In [ ]:
def show_graphic(dataset_name, metric, title):
    short_metric = metric[metric.find('(')+1: metric.find(')')]
    tradeoff_weights = results['Lambda'].drop_duplicates().to_list()
    mrmc_kl = results[(results['FairnessMeasure'] == 'kullback-leibler') & (results['Statistic'] == 'mean')][short_metric].to_list()
    mrmc_he = results[(results['FairnessMeasure'] == 'hellinger') & (results['Statistic'] == 'mean')][short_metric].to_list()
    mrmc_pe = results[(results['FairnessMeasure'] == 'pearson') & (results['Statistic'] == 'mean')][short_metric].to_list()

    mrmc_he_err = results[(results['FairnessMeasure'] == 'hellinger') & (results['Statistic'] == 'stdev')][short_metric].to_list()
    mrmc_he_err = [std/sqrt(5) for std in mrmc_he_err]
    mrmc_kl_err = results[(results['FairnessMeasure'] == 'kullback-leibler') & (results['Statistic'] == 'stdev')][short_metric].to_list()
    mrmc_kl_err = [std/sqrt(5) for std in mrmc_kl_err]
    mrmc_pe_err = results[(results['FairnessMeasure'] == 'pearson') & (results['Statistic'] == 'stdev')][short_metric].to_list()
    mrmc_pe_err = [std/sqrt(5) for std in mrmc_pe_err]
    
    # Plotando o gráfico com barras de erro
    plt.figure(figsize=(10, 6))
    plt.errorbar(tradeoff_weights, mrmc_kl, yerr=mrmc_kl_err, marker='o', linestyle='-', color='b', label='Kullback-Leibler', capsize=5) 
    plt.errorbar(tradeoff_weights, mrmc_he, yerr=mrmc_he_err, marker='s', linestyle='-', color='r', label='Hellinger', capsize=5) 
    plt.errorbar(tradeoff_weights, mrmc_pe, yerr=mrmc_pe_err, marker='^', linestyle='-', color='g', label='Pearson chi-quadrado', capsize=5)
    
    # Configurando os rótulos e título
    plt.xlabel(r'$\lambda$')
    plt.ylabel(metric)
    plt.title(title)
    
    # Definindo os valores do eixo x para incrementar de 0.1 em 0.1
    plt.xticks(np.arange(0.0, 1.1, 0.1))
    
    plt.legend()
    plt.grid(True)
    #plt.savefig(f'results/{dataset_name}/graphs/{dataset_name}_{metric}.pgf'.replace(' ', '_'))
    plt.savefig(f'results/{dataset_name}/graphs/{dataset_name}_{metric}.pdf'.replace(' ', '_'), bbox_inches='tight')
    plt.show()

In [ ]:
for metric in ['Mean Average Calibration Error (MACE)', 'Mean Rank Miscalibration (MRMC)', 'Mean Average Precision (MAP)', 'Mean Reciprocal Rank (MRR)']:
    print('=' * 10 + metric + '=' * 10)
    show_graphic('yahoo_movies', metric, 'Yahoo Movies com ALS')

In [ ]:
predictions_user_map

In [ ]:
distributions = Distributions(train.toPandas(), userColumn, itemColumn, genres_map)

In [ ]:
distributions.show_userProfileDist_userRecDist(predictions_user_map, 305)


# FBC-kNN

In [ ]:
df_genres = loader.genre_data

In [ ]:
df_genres

In [ ]:
df_expanded = df_genres['genres'].str.get_dummies(sep='|')

In [ ]:
df_final = pd.concat([df_genres[['item']], df_expanded], axis=1)

In [ ]:
df_final.index = df_final['item']

In [ ]:
df_mv_genres = df_final.drop(columns = ['item'])

In [ ]:
df_mv_genres

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
cosine_sim = cosine_similarity(df_mv_genres)

In [ ]:
df_cosine_sim = pd.DataFrame(cosine_sim, index = df_mv_genres.index, columns = df_mv_genres.index)

In [ ]:
df_cosine_sim

In [ ]:
similar_itens = list(df_cosine_sim.loc[1].sort_values(ascending=False).keys())[:102]
similar_itens.remove(1)
#rated_by_u = set(df_pandas[(df_pandas[userColumn] == 1) & (df_pandas[ratingColumn] > 0)][itemColumn].to_list())
#intersect = list(similar_itens.intersection(rated_by_u))[:101]

In [ ]:
def get_recommendatinon(movieId, userId, df_sim, df_ratings, k):
    similar_itens = list(df_sim.loc[movieId].sort_values(ascending=False).keys())[:k+2]
    similar_itens.remove(movieId)
    return similar_itens()

In [ ]:
#def get_recommendatinon(movieId, userId, df_sim, df_ratings, k):
#    similar_itens = set(df_sim.loc[movieId].sort_values(ascending=False).keys())
#    rated_by_u = set(df_ratings[(df_ratings[userColumn] == userId) & (df_ratings[ratingColumn] > 0)][itemColumn].to_list())
#    intersect = list(similar_itens.intersect(rated_by_u))[:k+1]