## Importações

In [15]:
import pandas as pd
import functions
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
from requests.exceptions import ReadTimeout
import discogs_client
from time import sleep
import json

## Criando sessão pyspark

In [16]:
import os
os.environ['SPARK_HOME'] = '/home/david/Documentos/UFABC/PGC/Codigos/code/Spark'
os.environ['PYSPARK_DRIVER_PYTHON'] = 'jupyter' 
os.environ['PYSPARK_DRIVER_OPTS'] = 'notebook'
os.environ['PYSPARK_PYTHON'] = 'python'

In [17]:
from pyspark.sql import SparkSession

In [18]:
spark = SparkSession.builder \
        .appName('PGC') \
        .getOrCreate()

24/08/05 20:13:53 WARN Utils: Your hostname, david-Nitro resolves to a loopback address: 127.0.1.1; using 192.168.15.5 instead (on interface wlp9s0)
24/08/05 20:13:53 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
24/08/05 20:13:54 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [19]:
spark.read.csv(
                                    './code/data/raw/lastfm/lastfm-dataset-360K/usersha1-artmbid-artname-plays.tsv',
                                    sep='\t',
                                    inferSchema=True,
                                    encoding='utf-8'
                                )

24/08/05 20:14:07 WARN GarbageCollectionMetrics: To enable non-built-in garbage collector(s) List(G1 Concurrent GC), users should configure it(them) to spark.eventLog.gcMetrics.youngGenerationGarbageCollectors or spark.eventLog.gcMetrics.oldGenerationGarbageCollectors

DataFrame[_c0: string, _c1: string, _c2: string, _c3: double]

## Spotify API

In [16]:
def get_genre(artistName):
    try:
        print(f'Artista: {artistName}')
        birdy_uri = 'spotify:artist:2WX2uTcsvV5OnS0inACecP'
        sp = spotipy.Spotify(client_credentials_manager=SpotifyClientCredentials(), requests_timeout=10, retries=10)
        
        result = sp.search(artistName)
        track = result['tracks']['items'][0]
        
        artist = sp.artist(track["artists"][0]["external_urls"]["spotify"])
        
        album = sp.album(track["album"]["external_urls"]["spotify"])
    
        print(f'Gente: {artist["genres"]}')
        if len(artist["genres"]) != 0:
            return artist["genres"]
        else:
            return album["genres"]
    except ReadTimeout:
        print('Timeout')

# Discogs API

In [17]:
d = discogs_client.Client('ExampleApplication/0.1',user_token='mDokHVmBVpXhrdfBYEJCJUgxEUipNOQhioIBNpvh')

def get_artist_genre_discogs(artist):
    results = d.search(artist, type='release')

    if len(results) > 0:
        id = results[0].id
        return d.release(id).genres
    else:
        print(f'Artista não encontrado: {artist}')
        return []

## Datasets utilizados

### Yahoo Movies

In [5]:
path_yahoo_movies = 'Datasets/Yahoo Movies/dataset/ydata-ymovies-user-movie-ratings-train-v1_0.txt'
df_yahoo_movies = pd.read_csv(path_yahoo_movies, sep='\t', names=['user_id', 'movie_id', 'rating', 'converted_rating'])

In [6]:
df

        user_id    movie_id  rating  converted_rating
0             1  1800029049      12                 5
1             1  1804857429       8                 4
2             1  1800030906      13                 5
3             1  1800018548      11                 5
4             1  1800256362       9                 4
...         ...         ...     ...               ...
211226     7642  1808405417      11                 5
211227     7642  1807839027       8                 4
211228     7642  1808405428      11                 5
211229     7642  1808429384      10                 4
211230     7642  1808404841       4                 2

[211231 rows x 4 columns]

In [12]:
print(functions.df_to_latex(df.head(), 'Primeiras 5 linhas do conjunto de dados Yahoo! Movies'))

\begin{table}[]
\centering
        \begin{tabular}{cccc}
\toprule
user_id & movie_id & rating & converted_rating \\
\midrule
1 & 1800029049 & 12 & 5 \\
1 & 1804857429 & 8 & 4 \\
1 & 1800030906 & 13 & 5 \\
1 & 1800018548 & 11 & 5 \\
1 & 1800256362 & 9 & 4 \\
\bottomrule
\end{tabular}

\caption{Primeiras 5 linhas do conjunto de dados Yahoo! Movies}
\end{table}

In [46]:
df_desc = pd.read_csv('../Datasets/Yahoo Movies/dataset/content-desc/movie_db_yoda', 
                      sep='\t', 
                      encoding='iso-8859-1', 
                      usecols = range(11),
                      names=['movie_id', 
                             'title', 
                             'synopsis', 
                             'running_time', 
                             'MPAA_rating', 
                             'reasons_for_the_MPAA_rating', 
                             'release_date_(yyyymmdd)',
                             'distributor',
                             'url_poster',
                             'pass',
                            'genres'])

In [47]:
df_desc = df_desc[['movie_id', 'title', 'genres']]

In [51]:
df_desc = df_desc[df_desc['genres'] != r'\N']

In [52]:
print(functions.df_to_latex(df_desc.head(), 'Primeiras 5 linhas do conjunto de dados de descrição de conteúdo do Yahoo! Movies'))

\begin{table}[]
\centering
        \begin{tabular}{ccc}
\toprule
movie_id & title & genres \\
\midrule
1800010969 & The 1985 Admiral's Cup (1997) & Special Interest \\
1800011786 & 984 - Prisoner of the Future (1984) & Science Fiction/Fantasy \\
1800011850 & A's All-Star Almanac (1987) & Special Interest \\
1800012991 & The Adventures of Annie Oakley (1953) & Western \\
1800013061 & The Adventures of Black Beauty 1 (1972) & Kids/Family \\
\bottomrule
\end{tabular}

\caption{Primeiras 5 linhas do conjunto de dados de descrição de conteúdo do Yahoo! Movies}
\end{table}

### Yahoo Music

In [3]:
df2 = pd.read_csv('code/data/raw/yahoo_music/dataset/ydata-ymusic-user-artist-ratings-v1_0.txt', 
                  sep='\t', 
                  names=['userId', 'artistId ', 'rating'])

In [4]:
df2.shape

(115579440, 3)

In [6]:
df2_names = pd.read_csv('code/data/raw/yahoo_music/dataset/ydata-ymusic-artist-names-v1_0.txt', 
                        sep='\t', 
                        names=['artistId', 'artistName'], 
                        usecols=range(2), 
                        encoding='iso-8859-1')

In [7]:
df2_names.shape

(97956, 2)

In [5]:
df2_names['artistName'] = df2_names['artistName'].str.replace('"', '') 
df2_names['artistName'] = df2_names['artistName'].str.replace("'", '')

In [6]:
test = pd.read_csv('../Datasets/Diversos/genres_music/archive/test.csv')
train = pd.read_csv('../Datasets/Diversos/genres_music/archive/train.csv')

In [7]:
train = train[['Artist Name', 'Class']].drop_duplicates()

In [8]:
df2_names = df2_names[df2_names['artistId']>0]
df2_names['artistName'] = df2_names['artistName'].str.lower()

#### Tentando recuperar gêneros com a Discogs

Importando dicionário previamente populado

In [5]:
json_path = 'Datasets/Yahoo Music/yahoo_music_genres.json'

with open(json_path) as json_file:
    artists_genres = json.load(json_file)

In [18]:
genres_mod = {'artistId': list(artists_genres.keys()), 
              'artistName': [v[0] for _, v in artists_genres.items()],
              'artistGenre': [v[1] for _, v in artists_genres.items()] 
             }

In [21]:
df_artists_gen = pd.DataFrame.from_dict(genres_mod)

In [29]:
df_artists_gen

      artistId      artistName             artistGenre
0      1000001         bobby o  [Hip Hop, Funk / Soul]
1      1000002         jimmy z         [Hip Hop, Rock]
2      1000003     68 comeback                  [Rock]
3      1000004     til tuesday             [Rock, Pop]
4      1000005  the (ec) nudes            [Jazz, Rock]
...        ...             ...                     ...
97949  1101110   14 karat soul           [Funk / Soul]
97950  1101111   the relativez               [Hip Hop]
97951  1101112       crooked i                  [Rock]
97952  1101113             skg            [Electronic]
97953  1101114       mac shawn                  [Rock]

[97954 rows x 3 columns]

In [15]:
artists_dict = df2_names.set_index('artistId').to_dict()['artistName']
max_key = max(map(int, artists_genres.keys()))
artists_dict = {k: v for k, v in artists_dict.items() if int(k) > max_key}


for id, artist in artists_dict.items():
    print(len(artists_genres))
    genre = get_artist_genre_discogs(artist)
    print(f'{artist}: {genre}')
    artists_genres[id] = (artist, genre)
    sleep(1)

1100416

In [28]:
artists_genres

{'1000001': ['bobby o', ['Hip Hop', 'Funk / Soul']],
 '1000002': ['jimmy z', ['Hip Hop', 'Rock']],
 '1000003': ['68 comeback', ['Rock']],
 '1000004': ['til tuesday', ['Rock', 'Pop']],
 '1000005': ['the (ec) nudes', ['Jazz', 'Rock']],
 '1000006': ['.38 special', ['Rock']],
 '1000008': ['1 + 1', ['Rock']],
 '1000009': ['1 of the girls', ['Hip Hop', 'Funk / Soul']],
 '1000010': ['1,000 clowns', ['Hip Hop']],
 '1000011': ['10 k.a.n.s', ['Hip Hop']],
 '1000012': ['10,000 maniacs', ['Rock']],
 '1000013': ['100 degrees celsius', ['Electronic']],
 '1000014': ['100 flowers', ['Rock']],
 '1000015': ['100 proof', ['Funk / Soul']],
 '1000016': ['1000 homo djs', ['Electronic']],
 '1000017': ['1000 mona lisas', ['Rock']],
 '1000018': ['101', ['Electronic', 'Rock', 'Pop']],
 '1000019': ['101 jade 4 u', ['Electronic']],
 '1000020': ['101 north', ['Jazz', 'Funk / Soul']],
 '1000021': ['101 strings', ['Pop']],
 '1000022': ['108', ['Electronic']],
 '1000023': ['10cc', ['Rock']],
 '1000024': ['10db', ['Electronic']],
 '1000025': ['11/5', ['Rock']],
 '1000026': ['112', ['Funk / Soul']],
 '1000027': ['116 soljaz', ['Hip Hop']],
 '1000028': ['12 cellists of berlin phil.', []],
 '1000029': ['12 gauge', ['Rock']],
 '1000030': ['13 engines', ['Electronic', 'Rock']],
 '1000032': ['14 bis', ['Rock', 'Latin']],
 '1000033': ['1487', ['Rock']],
 '1000034': ['16', ['Electronic']],
 '1000035': ['16 horsepower', ['Rock', 'Folk, World, & Country']],
 '1000036': ['16 volt', ['Electronic']],
 '1000037': ['17 pygmies', ['Folk, World, & Country']],
 '1000038': ['1755', ['Rock']],
 '1000039': ['1810 wurlitzer band organ', ['Funk / Soul']],
 '1000040': ['187 fac', ['Hip Hop']],
 '1000041': ['18th dye', ['Rock']],
 '1000043': ['1927', ['Rock', 'Pop']],
 '1000044': ['1952 broadway cast', ['Stage & Screen']],
 '1000045': ['1962 london studio cast', ['Stage & Screen']],
 '1000046': ['1962 off broadway cast', ['Stage & Screen']],
 '1000047': ['1963 broadway cast', ['Rock', 'Pop', 'Stage & Screen']],
 '1000048': ['1963 new york revival cast', ['Stage & Screen']],
 '1000049': ['1963 revival cast', ['Stage & Screen']],
 '1000050': ['1965 lincoln center cast', ['Stage & Screen']],
 '1000051': ['1966 lincoln center cast', ['Stage & Screen']],
 '1000052': ['1967 london cast', ['Pop', 'Stage & Screen']],
 '1000053': ['1976 broadway cast', ['Pop', 'Stage & Screen']],
 '1000054': ['1979 broadway cast', ['Rock', 'Pop', 'Stage & Screen']],
 '1000055': ['1983 broadway cast', ['Stage & Screen']],
 '1000056': ['1983 sadlers wells cast', ['Classical']],
 '1000057': ['1985 london cast', ['Stage & Screen']],
 '1000058': ['1986 broadway cast', ['Stage & Screen']],
 '1000059': ['1986 london studio cast', ['Electronic']],
 '1000060': ['1987 broadway cast', ['Stage & Screen']],
 '1000061': ['1987 casts', ['Stage & Screen']],
 '1000062': ['1987 studio cast', ['Stage & Screen']],
 '1000063': ['1988 london cast', ['Stage & Screen']],
 '1000064': ['1991 studio recording', ['Electronic', 'Rock']],
 '1000065': ['1992 broadway cast', ['Stage & Screen']],
 '1000066': ['1992 london cast', ['Stage & Screen']],
 '1000067': ['1993 london cast', ['Stage & Screen']],
 '1000068': ['1994 broadway cast recording', ['Stage & Screen']],
 '1000069': ['1994 london cast', ['Pop', 'Stage & Screen']],
 '1000070': ['1994 london palladium cast', ['Pop', 'Stage & Screen']],
 '1000071': ['1994 los angeles cast', ['Stage & Screen']],
 '1000072': ['1995 broadway cast recording', ['Stage & Screen']],
 '1000073': ['1995 london cast', ['Stage & Screen']],
 '1000074': ['1995 new york cast', ['Stage & Screen']],
 '1000075': ['1997 broadway cast', ['Stage & Screen']],
 '1000076': ['2 bad mice', ['Electronic']],
 '1000077': ['2 bigg mc', ['Hip Hop']],
 '1000078': ['2 black 2 strong', ['Electronic']],
 '1000079': ['2 deep', ['Hip Hop']],
 '1000080': ['2 die 4', ['Rock']],
 '1000081': ['2 fabiloa', []],
 '1000082': ['2 foot flame', ['Rock']],
 '1000083': ['2 in a room', ['Electronic']],
 '1000084': ['the 2 live crew', ['Hip Hop']],
 '1000085': ['2 lost sons', ['Rock']],
 '1000086': ['2 low', ['Rock']],
 '1000087': ['2 minutes hate', ['Rock']],
 '1000088': ['2 minutos', ['Rock']],
 '1000089': ['2 too many', ['Electronic']],
 '1000090': ['2 unlimited', ['Electronic']],
 '1000091': ['20 dead flowerchildren', []],
 '1000092': ['20 fingers', ['Electronic', 'Hip Hop']],
 '1000093': ['20-2-life', ['Hip Hop']],
 '1000094': ['20/20', ['Rock']],
 '1000095': ['2002', ['Electronic']],
 '1000096': ['20th century blues', ['Pop', 'Stage & Screen']],
 '1000097': ['21 guns', ['Rock']],
 '1000098': ['21st century dub', ['Electronic']],
 '1000099': ['22 brides', ['Rock']],
 '1000100': ['22 jacks', ['Rock']],
 '1000101': ['220 volt', ['Rock']],
 '1000102': ['23 degrees', ['Funk / Soul']],
 '1000103': ['24 gone', ['Funk / Soul']],
 '1000104': ['24-7 spyz', ['Rock']],
 '1000105': ['24-carat black', ['Funk / Soul']],
 '1000106': ['24k', ['Funk / Soul', 'Pop']],
 '1000107': ['25 is life', ['Rock']],
 '1000108': ['25 ta life', ['Rock']],
 '1000109': ['250 lbs. of blue', ['Electronic']],
 '1000110': ['25th anniversary revival cast', ['Stage & Screen']],
 '1000111': ['the 25th of may', ['Rock']],
 '1000112': ['27 devils joking', ['Rock']],
 '1000113': ['the 27 various',
  ['Electronic', 'Hip Hop', 'Rock', 'Funk / Soul', 'Pop']],
 '1000114': ['28th day', ['Rock']],
 '1000115': ['the 28th street crew', ['Electronic']],
 '1000116': ['29 palms', ['Rock']],
 '1000117': ['29died', ['Electronic']],
 '1000118': ['29th street saxophone quartet', ['Jazz']],
 '1000119': ['the 2awk', ['Hip Hop']],
 '1000120': ['2badcard', ['Electronic', 'Reggae']],
 '1000121': ['2nd chapter of acts', ['Rock', 'Pop']],
 '1000122': ['2nd ii none', ['Hip Hop']],
 '1000123': ['2nd nature', ['Electronic', 'Hip Hop']],
 '1000124': ['2nu', ['Electronic', 'Reggae', 'Non-Music', 'Pop']],
 '1000125': ['2pac', ['Hip Hop']],
 '1000126': ['3 car garage', ['Rock']],
 '1000127': ['3 day wheely', ['Rock']],
 '1000128': ['3 for all', ['Rock']],
 '1000130': ['3 johns', ['Rock', 'Folk, World, & Country']],
 '1000131': ['3lb. thrill', ['Rock']],
 '1000132': ['3 merry widows', ['Rock']],
 '1000133': ['3 mustaphas 3', ['Rock', 'Folk, World, & Country']],
 '1000134': ['3 penny needle', ['Rock']],
 '1000135': ['3 phase', ['Rock']],
 '1000136': ['3 steps from nowhere', ['Hip Hop', 'Funk / Soul']],
 '1000137': ['3 times krazy', ['Electronic', 'Funk / Soul', 'Pop']],
 '1000138': ['3-2', ['Hip Hop']],
 '1000139': ['3-2 get funky', ['Electronic']],
 '1000141': ['3-grand', ['Electronic', 'Funk / Soul']],
 '1000142': ['30 amp fuse', ['Rock']],
 '1000143': ['311', ['Rock']],
 '1000144': ['32 phreeze', ['Electronic', 'Funk / Soul']],
 '1000145': ['the 360 degree music', ['Rock', 'Funk / Soul', 'Pop']],
 '1000146': ['360s', ['Rock', 'Pop']],
 '1000147': ['36d', ['Rock', 'Pop']],
 '1000148': ['383 stroker', ['Rock']],
 '1000149': ['3d picnic', ['Rock']],
 '1000150': ['3ds', ['Pop', 'Stage & Screen']],
 '1000151': ['3rd avenue', ['Electronic']],
 '1000152': ['3rd bass', ['Hip Hop']],
 '1000153': ['3rd eye', ['Hip Hop']],
 '1000154': ['3rd force', ['Electronic', 'Jazz']],
 '1000155': ['3rd matinee', ['Electronic', 'Rock', 'Pop']],
 '1000156': ['3rd nation', ['Rock']],
 '1000157': ['3t', ['Electronic']],
 '1000159': ['4 by four', ['Hip Hop', 'Funk / Soul']],
 '1000160': ['4 corners', ['Electronic']],
 '1000161': ['4 deep', ['Electronic']],
 '1000163': ['4 non blondes', ['Rock']],
 '1000164': ['4 p.m.', ['Jazz']],
 '1000165': ['4 runner', ['Electronic', 'Stage & Screen']],
 '1000166': ['4-deep', ['Hip Hop']],
 '1000167': ['4-e', ['Electronic']],
 '1000168': ['4-fun', ['Pop']],
 '1000169': ['4-u', ['Electronic']],
 '1000170': ['411', ['Hip Hop', 'Funk / Soul']],
 '1000171': ['415', ['Rock']],
 '1000172': ['44 max', ['Hip Hop', 'Reggae', 'Funk / Soul', 'Pop']],
 '1000173': ['45 grave', ['Rock']],
 '1000174': ['45 king', ['Hip Hop']],
 '1000175': ['454 big block', ['Rock']],
 '1000176': ['48th highlanders', ['Brass & Military']],
 '1000177': ['49ers', ['Electronic']],
 '1000178': ['4him', ['Rock']],
 '1000179': ['4u', ['Electronic']],
 '1000180': ['the 5.6.7.8.s', ['Rock']],
 '1000181': ['50 guitars', ['Jazz', 'Folk, World, & Country']],
 '1000182': ['5150', ['Rock']],
 '1000183': ['52nd street', ['Jazz', 'Rock', 'Pop']],
 '1000184': ['54.40', ['Rock']],
 '1000185': ['5ive style', ['Rock']],
 '1000186': ['5ive-o', ['Hip Hop']],
 '1000187': ['5th ward boyz', ['Hip Hop']],
 '1000188': ['5th ward juvenilez', ['Hip Hop']],
 '1000189': ['5uus', ['Rock']],
 '1000190': ['6 1 dog', ['Rock']],
 '1000191': ['60 ft dolls', ['Rock']],
 '1000192': ['65dba', ['Hip Hop']],
 '1000193': ['69 boyz', ['Electronic']],
 '1000194': ['6l6', ['Electronic']],
 '1000195': ['the 6ths', ['Electronic', 'Rock']],
 '1000196': ['7', ['Electronic', 'Rock']],
 '1000197': ['7 seconds', ['Electronic', 'Hip Hop', 'Folk, World, & Country']],
 '1000198': ['7 speed vortex', ['Electronic']],
 '1000199': ['7 year bitch', ['Rock']],
 '1000200': ['7% solution', ['Jazz', 'Rock']],
 '1000201': ['700 miles', ['Rock']],
 '1000202': ['702', ['Funk / Soul']],
 '1000203': ['740 boyz', ['Electronic', 'Hip Hop']],
 '1000204': ['76% uncertain', ['Rock']],
 '1000205': ['7669', ['Hip Hop']],
 '1000206': ['77 luscious babes', ['Rock']],
 '1000207': ['the 77s', ['Rock']],
 '1000208': ['777', ['Electronic']],
 '1000209': ['the 7a3', ['Hip Hop']],
 '1000210': ['7lc', ['Electronic', 'Pop']],
 '1000211': ['7th ave. stompers', ['Jazz']],
 '1000212': ['7th stranger', ['Rock', 'Folk, World, & Country']],
 '1000213': ['8 1/2 souvenirs', ['Rock']],
 '1000214': ['8 eyed spy', ['Rock']],
 '1000215': ['8 storey window', ['Rock']],
 '1000216': ['801', ['Rock']],
 '1000217': ['808 state', ['Electronic']],
 '1000218': ['88 butterfly', ['Funk / Soul', 'Pop']],
 '1000219': ['88 fingers louie', ['Rock']],
 '1000220': ['88.3', ['Electronic', 'Rock']],
 '1000221': ['8off', ['Hip Hop']],
 '1000222': ['the 8th day', ['Funk / Soul']],
 '1000223': ['9 lazy 9', ['Electronic']],
 '1000224': ['9 ways to sunday', ['Electronic', 'Rock']],
 '1000225': ['90 m.p.h.', ['Rock']],
 '1000226': ['9353', ['Rock', 'Pop']],
 '1000227': ['95 south', ['Jazz', 'Funk / Soul', 'Stage & Screen']],
 '1000228': ['999', ['Rock']],
 '1000229': ['a 4 tiempos', ['Rock', 'Pop']],
 '1000230': ['a bullet for fidel', ['Rock']],
 '1000231': ['a capella kids', ['Electronic']],
 '1000232': ['a certain ratio', ['Electronic']],
 '1000233': ['a confederacy of dunces', ['Electronic']],
 '1000234': ['a few good men', ['Stage & Screen']],
 '1000235': ['a flock of seagulls', ['Electronic', 'Rock']],
 '1000236': ['a guy called gerald', ['Electronic']],
 '1000237': ['a house', ['Rock']],
 '1000238': ['a la carte brass & percussion',
  ['Jazz', 'Funk / Soul', 'Blues', 'Folk, World, & Country']],
 '1000239': ['aminiature', ['Rock']],
 '1000240': ['a minor forest', ['Rock']],
 '1000241': ['a plus', ['Jazz', 'Rock', 'Funk / Soul']],
 '1000242': ['a positive life', ['Hip Hop', 'Funk / Soul']],
 '1000243': ['a produce', ['Electronic']],
 '1000244': ['a small, good thing', ['Rock', 'Folk, World, & Country']],
 '1000245': ['a split second', ['Electronic']],
 '1000246': ['a subtle plague', ['Rock']],
 '1000247': ['a tribe called quest', ['Hip Hop']],
 '1000248': ['a witness', ['Electronic']],
 '1000249': ['a+', ['Rock']],
 '1000250': ['a-1 s.w.i.f.t.', ['Hip Hop', 'Funk / Soul']],
 '1000251': ['the a-bones', ['Rock']],
 '1000252': ['a-ha', ['Electronic', 'Rock']],
 '1000253': ['the a-strings', ['Jazz']],
 '1000254': ['a-town players', ['Electronic', 'Hip Hop']],
 '1000255': ['a.b. skhy', ['Rock', 'Funk / Soul', 'Blues']],
 '1000256': ['a.c.', ['Funk / Soul']],
 '1000257': ['a.c. acoustics', ['Rock']],
 '1000258': ['a.c. marias', ['Electronic']],
 '1000259': ['a.c.e.', ['Electronic']],
 '1000260': ['a.d.', ['Electronic']],
 '1000261': ['a.d.', ['Electronic']],
 '1000262': ['a.d.a.m./amy', ['Electronic', 'Pop']],
 '1000263': ['a.d.o.r.', ['Hip Hop', 'Funk / Soul']],
 '1000264': ['a.f.i.', ['Electronic', 'Rock']],
 '1000265': ['a.k.', ['Electronic']],
 '1000266': ['a.l.t.', ['Hip Hop']],
 '1000267': ['a.n.i.m.a.l.', ['Electronic']],
 '1000268': ['a.p.p.l.e.', ['Electronic']],
 '1000269': ['a.s.a.p.', ['Rock']],
 '1000270': ['the a.t.e.e.m.', ['Electronic', 'Rock', 'Pop']],
 '1000271': ['a.t.s.', ['Jazz']],
 '1000272': ['a;grumh', ['Electronic']],
 '1000273': ['aaak', ['Electronic']],
 '1000274': ['philip aaberg', ['Jazz', 'Folk, World, & Country']],
 '1000275': ['aahh!!! real monsters', ['Electronic', 'Hip Hop']],
 '1000276': ['aaliyah', ['Hip Hop', 'Funk / Soul', 'Pop']],
 '1000277': ['jay aaron', ['Classical']],
 '1000278': ['phil aaron trio', ['Jazz']],
 '1000279': ['robert aaron', ['Electronic']],
 '1000280': ['najat aatabou', ['Folk, World, & Country']],
 '1000281': ['ab logic', ['Electronic']],
 '1000282': ['alejandro abad', ['Pop']],
 '1000283': ['rita abadzi', ['Folk, World, & Country']],
 '1000284': ['abana ba nasery', ['Folk, World, & Country']],
 '1000285': ['greg abate quartet', ['Jazz']],
 '1000286': ['abba', ['Rock', 'Pop']],
 '1000287': ['abba rage', ['Electronic']],
 '1000288': ['rez abbasi', ['Jazz', 'Classical', 'Folk, World, & Country']],
 '1000289': ['abbey of mount angel choir', ['Classical']],
 '1000290': ['abbfinoosty', ['Rock']],
 '1000291': ['gregory abbott', ['Funk / Soul']],
 '1000292': ['abc', ['Funk / Soul']],
 '1000293': ['paiman abdali', ['Electronic']],
 '1000294': ['aboud abdel al', ['Jazz', 'Folk, World, & Country']],
 '1000295': ['abdelli', ['Folk, World, & Country']],
 '1000296': ['george abdo & flames of araby', ['Folk, World, & Country']],
 '1000297': ['paula abdul', ['Electronic', 'Hip Hop', 'Pop']],
 '1000298': ['ahmed abdul-malik', ['Jazz']],
 '1000299': ['alhaji ibrahim abdulai', ['Folk, World, & Country']],
 '1000300': ['ahmed abdullah', ['Jazz']],
 '1000301': ['safi abdullah',
  ['Reggae', 'Funk / Soul', 'Folk, World, & Country']],
 '1000302': ['abe lincoln story', ['Folk, World, & Country']],
 '1000303': ['keiko abe',
  ['Electronic', 'Classical', 'Folk, World, & Country']],
 '1000304': ['abecedarians', ['Rock']],
 '1000305': ['steve abee', ['Non-Music']],
 '1000306': ['john abercrombie', ['Jazz']],
 '1000307': ['tracy abercrombie', ['Jazz']],
 '1000308': ['jitendra abhisheki', ['Folk, World, & Country']],
 '1000309': ['abigail', ['Rock']],
 '1000310': ['dele abiodun', ['Funk / Soul', 'Folk, World, & Country']],
 '1000311': ['able tasmans', ['Rock']],
 '1000312': ['max able', ['Electronic']],
 '1000313': ['abolish', ['Rock']],
 '1000314': ['rabih abou-khalil', ['Jazz', 'Folk, World, & Country']],
 '1000315': ['camara aboubacar',
  ['Jazz', 'Latin', 'Funk / Soul', 'Folk, World, & Country']],
 '1000316': ['above the law', ['Electronic']],
 '1000317': ['above the ruins', ['Rock']],
 '1000318': ['mick abrahams', ['Rock']],
 '1000319': ['pablo abraira', ['Latin', 'Pop']],
 '1000320': ['colonel abrams', ['Electronic']],
 '1000321': ['muhal richard abrams orchestra', ['Jazz']],
 '1000322': ['abraxas pool', ['Rock', 'Latin']],
 '1000323': ['ralphy abreu y la banda magica', ['Latin']],
 '1000324': ['abscess', ['Rock']],
 '1000325': ['nathan abshire', ['Folk, World, & Country']],
 '1000326': ['absolute', ['Electronic']],
 '1000327': ['the absolute', ['Rock']],
 '1000328': ['abstinence', ['Rock', 'Pop']],
 '1000329': ['abstrac', ['Hip Hop']],
 '1000330': ['abundant life', ['Rock']],
 '1000331': ['the abyss', ['Rock']],
 '1000332': ['the abyssinian baptist choir', ['Funk / Soul']],
 '1000333': ['the abyssinians', ['Folk, World, & Country']],
 '1000334': ['ac black', ['Funk / Soul']],
 '1000335': ['ac/dc', ['Electronic']],
 '1000336': ['academy film orchestra', ['Jazz', 'Stage & Screen']],
 '1000337': ['acama', ['Electronic']],
 '1000338': ['acappella', ['Funk / Soul']],
 '1000339': ['acappella company', ['Pop']],
 '1000340': ['acapulco tropical', ['Latin']],
 '1000341': ['the accelerators', ['Rock']],
 '1000342': ['accept', ['Rock']],
 '1000343': ['accidental orchestra', ['Pop']],
 '1000344': ['accidental suicide', ['Rock']],
 '1000345': ['accidental tribe', ['Rock']],
 '1000346': ['the accused', ['Rock']],
 '1000347': ['accuser', ['Rock']],
 '1000348': ['accustomed to nothing', ['Rock']],
 '1000349': ['ace', ['Rock']],
 '1000350': ['ace deuce', ['Electronic']],
 '1000351': ['ace hard', ['Rock']],
 '1000352': ['ace juice', ['Hip Hop', 'Funk / Soul']],
 '1000353': ['ace of base', ['Electronic', 'Pop']],
 '1000354': ['buddy ace', ['Blues']],
 '1000356': ['acen', ['Electronic']],
 '1000357': ['acerina y su danzonera', ['Latin']],
 '1000359': ['acetone', ['Rock']],
 '1000360': ['ernie acevedo', ['Latin']],
 '1000361': ['aceyalone', ['Hip Hop']],
 '1000362': ['acid bath', ['Rock']],
 '1000363': ['acid bran', ['Electronic']],
 '1000364': ['acid king', ['Rock']],
 '1000365': ['acid test', ['Electronic']],
 '1000366': ['william ackerman', ['Rock']],
 '1000367': ['barbara acklin', ['Funk / Soul']],
 '1000368': ['alci acosta', ['Latin']],
 '1000369': ['checo acosta', ['Latin']],
 '1000370': ['george acosta', ['Electronic']],
 '1000371': ['acosta/russell', ['Electronic', 'Rock']],
 '1000372': ['acoustic alchemy', ['Jazz']],
 '1000373': ['acoustic junction', ['Rock', 'Pop', 'Folk, World, & Country']],
 '1000374': ['the acousticats', ['Folk, World, & Country']],
 '1000375': ['the acoustinauts', ['Rock', 'Pop']],
 '1000376': ['acoustix barbershop quartet', ['Pop']],
 '1000377': ['bill white acre', ['Folk, World, & Country']],
 '1000378': ['acrophet', ['Rock']],
 '1000379': ['acrostichon', ['Rock']],
 '1000381': ['action figures', ['Electronic']],
 '1000382': ['action man', ['Electronic', 'Rock', 'Pop']],
 '1000383': ['action painting', ['Rock']],
 '1000384': ['action swingers', ['Rock']],
 '1000385': ['actionslacks', ['Rock']],
 '1000386': ['active ingredient', ['Rock']],
 '1000387': ['acts magdalena', ['Rock']],
 '1000388': ['roy acuff', ['Folk, World, & Country']],
 '1000389': ['acumen', ['Electronic']],
 '1000390': ['acumen nation', ['Electronic', 'Rock']],
 '1000391': ['alex acuna & the unknowns', ['Jazz', 'Latin', 'Funk / Soul']],
 '1000392': ['ad vielle que pourra', ['Folk, World, & Country']],
 '1000393': ['adalberto', ['Latin']],
 '1000395': ['carol adam gipsy ensemble', []],
 '1000396': ['margie adam', ['Pop']],
 '1000397': ['adama drame', ['Folk, World, & Country']],
 '1000398': ['bryan adams', ['Rock', 'Pop']],
 '1000399': ['don adams', ['Rock']],
 '1000400': ['edie adams', ['Jazz', 'Pop']],
 '1000402': ['george adams', ['Jazz']],
 '1000403': ['greg adams', ['Folk, World, & Country']],
 '1000404': ['johnny adams', ['Jazz', 'Blues']],
 '1000405': ['julie adams & the rhino boys', ['Rock']],
 '1000406': ['milton adams', ['Funk / Soul']],
 '1000407': ['oleta adams', ['Jazz', 'Funk / Soul']],
 '1000408': ['paul adams', ['Rock', 'Pop']],
 '1000409': ['pepper adams', ['Jazz']],
 '1000410': ['terry adams',
  ['Jazz', 'Rock', 'Funk / Soul', 'Blues', 'Folk, World, & Country']],
 '1000411': ['tom adams', ['Rock', 'Pop']],
 '1000412': ['yolanda adams', ['Funk / Soul']],
 '1000413': ['adamski', ['Electronic']],
 '1000414': ['barry adamson', ['Electronic']],
 '1000415': ['adastra', ['Electronic']],
 '1000416': ['c.c. adcock', ['Blues', 'Folk, World, & Country']],
 '1000417': ['eddie adcock', ['Folk, World, & Country']],
 '1000418': ['cannonball adderley', ['Jazz']],
 '1000419': ['nat adderley', ['Jazz']],
 '1000420': ['mustapha tettey addy', ['Folk, World, & Country']],
 '1000421': ['obo addy', ['Folk, World, & Country']],
 '1000422': ['king sunny ade', ['Folk, World, & Country']],
 '1000423': ['adeva', ['Electronic']],
 '1000424': ['segun adewale', ['Folk, World, & Country']],
 '1000425': ['the adicts', ['Rock']],
 '1000426': ['adiemus', ['Electronic', 'Folk, World, & Country']],
 '1000427': ['adioa', ['Reggae']],
 '1000429': ['hasil adkins', ['Rock']],
 '1000430': ['paul adkins/borderline band', ['Folk, World, & Country']],
 '1000431': ['trace adkins', ['Folk, World, & Country', 'Stage & Screen']],

In [41]:
max(map(int, artists_genres.keys())) - max_key

16649

#### Salvando o JSON em disco

In [20]:
with open(json_path, 'w') as fp:
    json.dump(artists_genres, fp)

In [22]:
df2_names

       artistId      artistName
2       1000001         bobby o
3       1000002         jimmy z
4       1000003     68 comeback
5       1000004     til tuesday
6       1000005  the (ec) nudes
...         ...             ...
97951   1101110   14 karat soul
97952   1101111   the relativez
97953   1101112       crooked i
97954   1101113             skg
97955   1101114       mac shawn

[97954 rows x 2 columns]

In [35]:
df_gen = pd.DataFrame(artists_genres.items(), columns=['artistId', 'artistName'])

In [33]:
df_gen[['valor1', 'nested_list']] = pd.DataFrame(df_gen['col1'].tolist(), index=df.index)

AttributeError: 'list' object has no attribute 'get'

In [36]:
print(functions.df_to_latex(df2_names.head(), 'Primeiras 5 linhas do conjunto de nomes de artistas do Yahoo! Music'))

\begin{table}[]
\centering
        \begin{tabular}{cc}
\toprule
artistId & artistName \\
\midrule
-100 & Not Applicable \\
-99 & Unknown Artist \\
1000001 & Bobby "O" \\
1000002 & Jimmy "Z" \\
1000003 & '68 Comeback \\
\bottomrule
\end{tabular}

\caption{Primeiras 5 linhas do conjunto de nomes de artistas do Yahoo! Music}
\end{table}

In [15]:
print(functions.df_to_latex(df2.head(), 'Primeiras 5 linhas do conjunto de dados Yahoo! Music'))

\begin{table}[]
\centering
        \begin{tabular}{ccc}
\toprule
userId & artistId  & rating \\
\midrule
1 & 1000125 & 90 \\
1 & 1006373 & 100 \\
1 & 1006978 & 90 \\
1 & 1007035 & 100 \\
1 & 1007098 & 100 \\
\bottomrule
\end{tabular}

\caption{Primeiras 5 linhas do conjunto de dados Yahoo! Music}
\end{table}

-------------------------------

### LastFm

In [5]:
import polars as pl
import pandas as pd
import chardet

In [10]:
    def _detect_encoding(file_path):
        with open(file_path, 'rb') as file:
            raw_data = file.read()
            result = chardet.detect(raw_data)
            return result['encoding']

In [23]:
_detect_encoding('/code/data/raw/lastfm/usersha1-artmbid-artname-plays.tsv')

FileNotFoundError: [Errno 2] No such file or directory: '/code/data/raw/lastfm/usersha1-artmbid-artname-plays.tsv'

In [13]:
lastfm = pl.read_csv('code/data/raw/lastfm/lastfm-dataset-360K/usersha1-artmbid-artname-plays.tsv', 
                    separator = '\t',
                    encoding = 'utf-8',
                    new_columns=['userId', 'artistId', 'artistName', 'plays'],
                    has_header = False)
                    #lineterminator = '\n',
                    #nrows = 17559530)

ComputeError: could not parse `"ÂÈÎ-66", İñòğàäíûé îğêåñòğ, Àëåêñåé Ìàæóêîâ` as dtype `str` at column 'column_3' (column number 3)

The current offset in the file is 437770335 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `dtypes` argument
- setting `ignore_errors` to `True`,
- adding `"ÂÈÎ-66", İñòğàäíûé îğêåñòğ, Àëåêñåé Ìàæóêîâ` to the `null_values` list.

Original error: ```string field is not properly escaped```

In [27]:
df_lastfm = spark.read.csv('code/data/raw/lastfm/lastfm-dataset-360K/usersha1-artmbid-artname-plays.tsv', 
                           sep=r'\t', 
                           inferSchema = True)

In [29]:
columns = ['userId', 'artistId', 'artistName', 'plays']
df_lastfm = df_lastfm.toDF(*columns)

In [35]:
df_lastfm.count()

17559530

In [36]:
df_artists = df_lastfm.select('artistId', 'artistName')

In [38]:
df_artists = df_artists.dropDuplicates()

In [39]:
df_artists.count()

295257

In [42]:
df_artists = df_artists.coalesce(1)
df_artists.write.csv('lastfm_artists.csv', header=True)

#### Obtendo gêneros

Obtendo dicionário com gêneros previamente salvos

In [29]:
json_path = 'Datasets/lastfm/lastfm_music_genres.json'

try:
    with open(json_path) as json_file:
        artists_genres = json.load(json_file)
except:
    artists_genres = {}

In [3]:
lastfm_artists = lastfm[['artistId', 'artistName']].drop_duplicates()

In [31]:
lastfm_artists.shape

(295262, 2)

In [4]:
lastfm
artists_dict = lastfm_artists.set_index('artistId').to_dict()['artistName']

In [6]:
with open('lastfm_artists.json', 'w') as fp:
    json.dump(artists_dict, fp)

In [34]:
if len(artists_genres) > 0:
    max_key = max(map(int, artists_genres.keys()))
else:
    max_key = -1
    
# artists_dict = {k: v for k, v in artists_dict.items() if int(k) > max_key}


for id, artist in artists_dict.items():
    print(len(artists_genres))
    genre = get_artist_genre_discogs(artist)
    print(f'{artist}: {genre}')
    artists_genres[id] = (artist, genre)
    sleep(1)

0
betty blowtorch: ['Rock']
1
die ärzte: ['Rock']
2
melissa etheridge: ['Rock']
3
elvenking: ['Rock']
4
juliette lewis and the licks: ['Rock']
5
red hot chili pippers: ['Rock']
6
magica: ['Electronic']
7
the black dahlia murder: ['Rock']
8
murmurs: ['Rock']
9
lunachicks: ['Rock']
10
walls of jericho: ['Rock']
11
letzte instanz: ['Non-Music', 'Pop', 'Folk, World, & Country']
12
goldfrapp: ['Electronic', 'Non-Music', 'Pop']
13
horrorpops: ['Rock']
14
butchies, the: ['Rock']
15
jack off jill: ['Rock']
16
babes in toyland: ['Rock']
17
Artista não encontrado: dropkick murfhys
dropkick murfhys: []
18
all my faults: ['Funk / Soul']
19
le tigre: ['Electronic']
20
schandmaul: ['Rock', "Children's"]
21
edguy: ['Rock']
22
Artista não encontrado: maximum the harmone
maximum the harmone: []
23
all ends: ['Funk / Soul']
24
johnson jack: ['Jazz']
25
eluveitie: ['Rock']
26
rasputina: ['Rock']
27
Artista não encontrado: london afrer midnight
london afrer midnight: []
28
the killers: ['Rock']
29
夢中夢: ['Rock']
30
judas priest: ['Rock']
31
rob zombie: ['Rock']
32
the boss hoss: ['Rock']
33
b.o.c.: ['Rock']
34
sandra nasić: ['Electronic', 'Rock', 'Pop']
35
john mayer: ['Rock', 'Blues']
36
sleater-kinney: ['Rock']
37
who: ['Rock']
38
disciple: ['Reggae']
39
tanzwut: ['Electronic', 'Rock']
40
guano apes: ['Rock']
41
rolling stones: ['Rock', 'Blues']
42
little big town: ['Folk, World, & Country']
43
team dresch: ['Rock']
44
betty: ['Funk / Soul']
45
l7: ['Rock']
46
bif naked: ['Rock']
47
girlschool: ['Rock']
48
the wallflowers: ['Rock']
49
the most serene republic: ['Rock']
50
the stars: ['Electronic']
51
broken social scene: ['Rock']
52
have heart: ['Rock', 'Pop']
53
luminous orange: ['Rock']
54
boris: ['Rock']
55
artic monkeys: ['Rock']
56
bright eyes: ['Rock', 'Pop', 'Stage & Screen']
57
coaltar of the deepers: ['Rock']
58
polar bear club: ['Rock']
59
the libertines: ['Rock']
60
death from above 1979: ['Rock']
61
owl city: ['Electronic', 'Pop']
62
coldplay: ['Electronic']
63
okkervil river: ['Rock']
64
jim sturgess: ['Rock', 'Pop', 'Stage & Screen']
65
deerhoof: ['Rock']
66
fear before the march of flames: ['Rock']
67
breathe carolina: ['Electronic', 'Rock']
68
mstrkrft: ['Electronic']
69
the arcade fire: ['Rock']
70
the strokes: ['Rock']
71
cancer bats: ['Rock']
72
the  honorary title: ['Rock']
73
michio kurihara: ['Rock']
74
management: ['Electronic']
75
queen: ['Rock']
76
the secret handshake: ['Blues']
77
animal collective: ['Electronic', 'Rock']
78
heavyheavylowlow: ['Electronic']
79
hothot heat: ['Rock']
80
hadouken!: ['Electronic', 'Reggae']
81
wombats , the: ['Pop']
82
ai aso: ['Rock', 'Pop', 'Folk, World, & Country']
83
boris with michio kurihara: ['Rock']
84
uffie: ['Electronic', 'Hip Hop']
85
last shadow puppets: ['Rock']
86
boys noize: ['Electronic', 'Rock']
87
built to spill: ['Rock']
88
nujabes: ['Hip Hop']
89
the rocket summer: ['Rock']
90
little dragon.: ['Electronic', 'Funk / Soul']
91
boris with merzbow: ['Rock']
92
album leaf, the: ['Electronic', 'Rock']
93
microphones: ['Rock', 'Folk, World, & Country']
94
Artista não encontrado: simmian mobile disco
simmian mobile disco: []
95
m.i.a.: ['Funk / Soul']
96
deathcab for cutie: ['Rock']
97
patrick wolf: ['Electronic', 'Rock', 'Pop']
98
the fiery furnaces: ['Rock']
99
digitalism: ['Electronic']
100
current 93: ['Electronic', 'Rock']
101
elph vs. coil: ['Electronic']
102
andrew liles: ['Electronic']
103
6  organs of admittance: ['Rock']
104
sixteen horsepower: ['Rock', 'Folk, World, & Country']
105
the angels of light: ['Rock']
106
legendary pink dots: ['Electronic']
107
charalambides: ['Rock']
108
festival: ['Jazz', 'Rock', 'Latin']
109
fern knight: ['Rock', 'Folk, World, & Country']
110
nick cave and the bad seeds: ['Rock']
111
fovea hex: ['Electronic', 'Pop']
112
amanda rogers: ['Rock', 'Pop']
113
lux interna: ['Electronic', 'Rock']
114
nalle: ['Rock', 'Blues', 'Pop']
115
Artista não encontrado: antony and the jjhnsons
antony and the jjhnsons: []
116
nadler, marissa: ['Rock']
117
the silver mt. zion memorial orchestra & tra-la-la band & choir: ['Rock']
118
einsturzende neubauten: ['Rock']
119
marc almond: ['Electronic', 'Pop']
120
mariee sioux: ['Folk, World, & Country']
121
Artista não encontrado: björk guğmunsdóttir
björk guğmunsdóttir: []
122
bill fay: ['Rock']
123
nurse with wound: ['Electronic']
124
baby dee: ['Folk, World, & Country']
125
ghq: ['Electronic']
126
daniel higgs: ['Rock', 'Blues', 'Folk, World, & Country']
127
flairck: ['Pop', 'Folk, World, & Country']
128
jack rose: ['Rock', 'Blues']
129
castanets: ['Blues']
130
john jacob niles: ['Non-Music', 'Folk, World, & Country']
131
the revolutionary army of the infant jesus: ['Electronic', 'Rock']
132
carter tutti: ['Electronic']
133
the one ensemble of daniel padden: ['Electronic', 'Rock']
134
orion rigel dommisse: ['Folk, World, & Country']
135
jocelyn pook: ['Classical', 'Folk, World, & Country', 'Stage & Screen']
136
matmos: ['Electronic']
137
ulver: ['Rock']
138
ane brun: ['Electronic']
139
soisong: ['Electronic']
140
a hawk and a hacksaw: ['Electronic', 'Folk, World, & Country']
141
frank london: ['Jazz']
142
michael gira: ['Rock', 'Non-Music']
143
larkin grimm: ['Rock', 'Folk, World, & Country']
144
pelt: ['Rock']
145
jean parlette: ['Electronic', 'Folk, World, & Country']
146
opeth: ['Rock']
147
Artista não encontrado: cannbal corpse
cannbal corpse: []
148
elis: ['Jazz', 'Latin']
149
amoral: ['Electronic', 'Rock']
150
amon amarth: ['Rock']
151
riverside: ['Electronic']
152
Artista não encontrado: dark tranquiility
dark tranquiility: []
153
atrocity (us): ['Electronic', 'Hip Hop']
154
kromlek: ['Rock']
155
kamelot: ['Electronic']
156
november's doom: ['Rock']
157
poe: ['Electronic', 'Classical']
158
suzanina: ['Electronic']
159
dido: ['Electronic']
160
stone temple pilots: ['Rock']
161
civilian: ['Rock', 'Pop']
162
katatonia: ['Rock']
163
ark: ['Rock']
164
circus maximus: ['Rock']
165
Artista não encontrado: dimmmu borgir
dimmmu borgir: []
166
death: ['Rock']
167
manegarm: ['Rock']
168
cynic: ['Electronic']
169
korpiklaani: ['Rock']
170
my dying bride: ['Rock']
171
brujería: ['Latin', 'Funk / Soul']
172
agalloch: ['Rock']
173
alice in chains: ['Rock']
174
Artista não encontrado: jhoann sebastian bach
jhoann sebastian bach: []
175
kalmah: ['Rock']
176
farmakon: ['Rock']
177
cob: ['Electronic']
178
dragonforce: ['Electronic']
179
dredg: ['Rock']
180
green carnation: ['Rock']
181
pain of salvation: ['Rock']
182
rhapsody of fire: ['Rock']
183
the mars volta: ['Rock']
184
tool: ['Rock']
185
arch enemy: ['Rock']
186
at the gates: ['Rock']
187
compay sagundo: ['Latin']
188
ensiferum: ['Rock']
189
naglfar: ['Electronic']
190
nevermore: ['Rock']
191
old man's child: ['Rock']
192
shade empire: ['Rock']
193
system of  a down: ['Rock']
194
tristania: ['Rock']
195
Artista não encontrado: debendra banhart
debendra banhart: []
196
boards of canada: ['Electronic']
197
coco rosie: ['Electronic', 'Rock']
198
aphex twin: ['Electronic']
199
atmosphere: ['Rock']
200
joanna newsom: ['Rock']
201
aïr: ['Jazz', 'Rock', 'Funk / Soul', 'Folk, World, & Country']
202
portishead: ['Electronic']
203
massive attack: ['Electronic']
204
plaid: ['Electronic']
205
fog: ['Electronic', 'Hip Hop', 'Rock']
206
prefuse 73: ['Electronic', 'Hip Hop']
207
m83: ['Electronic', 'Rock']
208
the flashbulb: ['Rock']
209
pavement: ['Electronic', 'Funk / Soul']
210
Artista não encontrado: amon tobbin
amon tobbin: []
211
sage francis: ['Hip Hop', 'Non-Music']
212
four tet: ['Electronic']
213
brother ali: ['Hip Hop']
214
max richter: ['Electronic', 'Classical']
215
why?: ['Electronic']
216
autechre: ['Electronic']
217
radiohead: ['Hip Hop']
218
yokota susumu: ['Electronic']
219
electrelane: ['Electronic', 'Rock']
220
neutral milk hotel: ['Rock']
221
bent: ['Jazz', 'Rock']
222
vetiver: ['Electronic', 'Rock']
223
k-the-i???: ['Electronic', 'Hip Hop']
224
illogic: ['Electronic']
225
annie: ['Rock']
226
broadcast: ['Electronic', 'Rock']
227
Artista não encontrado: the basty boys
the basty boys: []
228
aesop rock: ['Hip Hop']
229
mf doom: ['Hip Hop', 'Jazz', 'Pop']
230
the books: ['Hip Hop']
231
bibio: ['Electronic', 'Rock']
232
rachels: ['Rock']
233
Artista não encontrado: architecture in elsinki
architecture in elsinki: []
234
bola: ['Electronic', 'Rock', 'Pop', "Children's"]
235
isan: ['Folk, World, & Country']
236
múm: ['Electronic']
237
elliotte smith: ['Hip Hop']
238
caribou: ['Rock', 'Pop']
239
hold steady,the: ['Rock']
240
mogwai: ['Electronic', 'Rock']
241
justice: ['Electronic']
242
Artista não encontrado: sigur ro?s
sigur ro?s: []
243
clutch: ['Rock']
244
white denim: ['Jazz', 'Rock']
245
the go! team: ['Rock', 'Funk / Soul']
246
beatles, the: ['Rock', 'Pop']
247
2manydjs: ['Electronic', 'Rock', 'Pop']
248
tv on the radio: ['Rock']
249
kyuss: ['Rock']
250
dj shadow: ['Electronic', 'Hip Hop', 'Funk / Soul', 'Blues']
251
(a) tribe called quest: ['Hip Hop']
252
cinematic orchestra: ['Stage & Screen']
253
beck: ['Jazz']
254
bon iver: ['Rock']
255
Artista não encontrado: rã¶yksopp
rã¶yksopp: []
256
rex the dog: ['Electronic']
257
bonobo: ['Electronic']
258
Artista não encontrado: deadmru5
deadmru5: []
259
the decemberists: ['Rock']
260
earth: ['Electronic', 'Hip Hop']
261
Artista não encontrado: snow potrol
snow potrol: []
262
battles: ['Rock']
263
metronomy: ['Electronic', 'Pop']
264
dj format: ['Latin', 'Funk / Soul']
265
prodigy the: ['Electronic']
266
Artista não encontrado: lemon jellly
lemon jellly: []
267
pink fluid: ['Rock']
268
rjd2: ['Hip Hop']
269
flaming lips: ['Rock']
270
alasdair fraser, paul machlis: ['Folk, World, & Country']
271
passion pit: ['Rock']
272
holy fuck: ['Electronic', 'Rock']
273
Artista não encontrado: michael jeckson
michael jeckson: []
274
late of the pier: ['Electronic', 'Rock']
275
flight of the conchords.: ['Rock', 'Pop', 'Folk, World, & Country', 'Stage & Screen']
276
muse: ['Rock']
277
fleetwood mac: ['Rock']
278
led zeppelin.: ['Rock']
279
stam1na: ['Rock']
280
dream theater: ['Rock']
281
ac dc: ['Electronic']
282
metallica: ['Rock']
283
iron maiden: ['Rock']
284
Artista não encontrado: bob marleythe wailers
bob marleythe wailers: []
285
megadeth: ['Rock', 'Non-Music']
286
trivium: ['Rock']
287
raappana: ['Reggae']
288
nightwish[: ['Rock']
289
kotiteollisuus: ['Rock']
290
sublime: ['Rock']
291
viikate: ['Rock']
292
volbeat: ['Rock']
293
guns & roses: ['Reggae']
294
bon jovi: ['Rock']
295
dio: ['Rock']
296
soja: ['Reggae']
297
scorpions: ['Rock']
298
terÄsbetoni: ['Rock']
299
nopsajalka: ['Hip Hop', 'Reggae']
300
paramore: ['Rock', 'Pop']
301
the darkness: ['Electronic']
302
soul captain band: ['Reggae']
303
asa: ['Rock', 'Folk, World, & Country']
304
tarot: ['Electronic', 'Rock']
305
klamydia: ['Rock']
306
gentleman: ['Jazz', 'Funk / Soul', 'Folk, World, & Country']
307
motley crue: ['Rock']
308
manowar: ['Rock']
309
Artista não encontrado: killswitch engade
killswitch engade: []
310
slayer: ['Rock']
311
in flames: ['Rock']
312
skid row: ['Rock']
313
stone: ['Rock']
314
Artista não encontrado: bullet for my valeintine
bullet for my valeintine: []
315
mokoma: ['Rock']
316
pantera: ['Rock']
317
brother firetribe: ['Rock']
318
hurriganes: ['Rock']
319
norther: ['Rock']
320
stratovarius: ['Rock']
321
kiuas: ['Rock']
322
Artista não encontrado: ozzy osbone
ozzy osbone: []
323
pin: ['Rock']
324
feel: ['Electronic', 'Funk / Soul']
325
eltron john: ['Electronic']
326
orgy: ['Electronic']
327
brandy: ['Hip Hop', 'Funk / Soul']
328
pet shop boys: ['Electronic', 'Pop']
329
sade: ['Jazz', 'Funk / Soul']
330
belinda carlisle: ['Rock']
331
eurythmics: ['Electronic', 'Pop']
332
mike oldfield: ['Rock', 'Pop']
333
daryl hall & john oates: ['Rock']
334
chris rea: ['Rock']
335
laura branigan: ['Electronic', 'Pop']
336
the waterboys: ['Rock']
337
maciej silski: ['Rock', 'Pop']
338
leona lewis: ['Electronic', 'Funk / Soul', 'Pop']
339
Artista não encontrado: gerge micheal
gerge micheal: []
340
black: ['Electronic']
341
frozen silence: ['Jazz']
342
sweet coffee: ['Rock']
343
blackfield: ['Rock']
344
cindy lauper: ['Pop']
345
pseudo echo: ['Electronic']
346
desirless: ['Electronic', 'Hip Hop', 'Reggae']
347
Artista não encontrado: limip bizkit
limip bizkit: []
348
modern talking: ['Electronic']
349
rihanna & jay-z: ['Hip Hop', 'Funk / Soul', 'Pop']
350
aha: ['Electronic']
351
link'in park: ['Rock']
352
zimmer: ['Classical', 'Stage & Screen']
353
Artista não encontrado: knelly furtado
knelly furtado: []
354
madonna: ['Electronic', 'Pop']
355
blink - 182: ['Rock']
356
dave gahan: ['Electronic']
357
kelly clarkson: ['Non-Music', 'Pop']
358
lucie silvas: ['Pop', 'Folk, World, & Country']
359
natalie imbruglia: ['Pop']
360
michelle branch: ['Rock']
361
delta goodrem: ['Pop']
362
new order: ['Electronic', 'Rock', 'Pop']
363
seal: ['Electronic', 'Rock', 'Funk / Soul', 'Pop']
364
atomic kitten: ['Electronic', 'Pop']
365
backstreet boys: ['Pop']
366
mary j. bige: ['Rock']
367
negative: ['Rock']
368
Artista não encontrado: justiin timberlake
justiin timberlake: []
369
savage garden: ['Electronic', 'Rock', 'Pop']
370
nérina pallot: ['Rock']
371
erasure: ['Electronic', 'Pop']
372
boy george and culture club: ['Electronic', 'Pop']
373
mr oizo: ['Electronic']
374
robbie willam: ['Pop', 'Folk, World, & Country']
375
black eyed beas: ['Rock']
376
antonio_orozco: ['Pop']
377
decai: ['Latin', 'Pop']
378
kiko y shara: ['Latin', 'Pop']
379
marc anthony: ['Latin']
380
manuel carrasco: ['Latin', 'Pop']
381
mika: ['Rock', 'Funk / Soul']
382
juanes: ['Latin']
383
Artista não encontrado: la oreha de van gogh
la oreha de van gogh: []
384
melendi: ['Rock', 'Latin', 'Pop']
385
amaral: ['Rock', 'Pop', 'Folk, World, & Country']
386
andy y lucas: ['Latin', 'Pop']
387
chambao: ['Latin', 'Pop']
388
chayanne: ['Latin', 'Pop']
389
cristian: ['Electronic']
390
Artista não encontrado: christina aguilerа
christina aguilerа: []
391
craig david: ['Electronic', 'Hip Hop']
392
luís fonsi: ['Latin', 'Pop']
393
sergio contreras: ['Hip Hop', 'Pop']
394
ana torroja: ['Pop']
395
beyoncÉ knowles: ['Hip Hop', 'Reggae', 'Funk / Soul', 'Pop']
396
bustamante: ['Latin', 'Pop']
397
camila: ['Latin', 'Pop']
398
colbie caillat: ['Pop']
399
coti: ['Rock', 'Latin', 'Pop']
400
david bisbal: ['Latin', 'Pop']
401
edurne: ['Rock', 'Pop']
402
fito y fitipaldi: ['Rock']
403
hanna: ['Electronic', 'Pop']
404
malu: ['Funk / Soul', 'Non-Music']
405
paulina rubio: ['Electronic', 'Pop']
406
rosana: ['Funk / Soul', 'Pop']
407
t.a.t.u: ['Electronic', 'Pop']
408
 amy winehouse: ['Pop']
409
efecto mariposa: ['Pop']
410
el_arrebato: ['Latin']
411
enrique: ['Rock', 'Latin', 'Pop']
412
jenifer lópez: ['Hip Hop', 'Latin', 'Pop']
413
mecano: ['Electronic']
414
phill collins-: ['Rock', 'Pop']
415
sean kingston: ['Hip Hop', 'Reggae', 'Funk / Soul', 'Pop']
416
u2: ['Rock']
417
dub fx: ['Electronic']
418
boxcar racer: ['Rock', 'Pop']
419
zebrahead: ['Rock']
420
oakenfold: ['Electronic']
421
pendulum: ['Rock']
422
ronald_jenkees: ['Electronic', 'Hip Hop']
423
sum41: ['Rock', 'Pop']
424
angel and airwaves: ['Rock']
425
haggard: ['Folk, World, & Country']
426
Artista não encontrado: alian ant farm
alian ant farm: []
427
offspring: ['Rock']
428
Океан Эльзы: ['Rock']
429
lord of the dance: ['Electronic', 'Folk, World, & Country']
430
crystal method: ['Electronic', 'Pop']
431
kawada mami: ['Electronic', 'Rock', 'Pop']
432
eminem: ['Hip Hop']
433
qemists, the: ['Electronic']
434
silverstein: ['Non-Music', 'Folk, World, & Country']
435
rise against: ['Rock']
436
БумБокс: ['Hip Hop', 'Rock', 'Funk / Soul']
437
scum of the earth: ['Rock']
438
blu mar ten: ['Electronic']
439
bomfunk mc's: ['Electronic']
440
vanessa mae: ['Rock', 'Pop', 'Classical']
441
ТарТак: ['Hip Hop', 'Rock']
442
drop dead,gorgeous: ['Electronic', 'Rock']
443
flying steps: ['Electronic', 'Funk / Soul']
444
drumattic twins: ['Electronic']
445
andrew wk: ['Rock']
446
hoobastank: ['Rock']
447
dover: ['Electronic', 'Pop']
448
bodyjar: ['Rock']
449
southside rockers: ['Electronic', 'Hip Hop']
450
prodigy (of mobb deep): ['Hip Hop']
451
Artista não encontrado: future phrophecies
future phrophecies: []
452
coulton, jonathan: ['Rock']
453
blessthefall: ['Rock']
454
nubreed & luke chable: ['Electronic']
455
franz ferdinand: ['Rock']
456
johannes linstead: ['Latin']
457
infected mushroom: ['Electronic']
458
darude: ['Electronic']
459
akira yamaoka: ['Electronic', 'Jazz']
460
aqua: ['Electronic']
461
clawfinger: ['Rock']
462
dusty kid: ['Electronic']
463
senses fail*: ['Rock']
464
commix: ['Electronic']
465
panic! at the  disco: ['Rock']
466
enigma: ['Jazz']
467
Artista não encontrado: fafboy slim
fafboy slim: []
468
krs-one: ['Hip Hop']
469
drowing pool: ['Rock']
470
placebo: ['Rock']
471
david & the citizens: ['Rock']
472
kent: ['Rock']
473
säkert!: ['Rock']
474
detektivbyrån: ['Electronic', 'Folk, World, & Country']
475
lars winnerbäck: ['Pop', 'Folk, World, & Country']
476
raymond & maria: ['Classical']
477
Artista não encontrado: tegan and aara
tegan and aara: []
478
knife the: ['Electronic', 'Pop']
479
tgr lou: ['Rock']
480
håkan hällström: ["Children's"]
481
david fridlund: ['Rock']
482
the ark: ['Rock']
483
alice in videoland: ['Electronic', 'Rock', 'Pop']
484
timo räisänen: ['Rock']
485
cardigans: ['Rock', 'Pop']
486
bloc party: ['Electronic', 'Rock']
487
oasis: ['Rock', 'Non-Music']
488
sahara hotnights: ['Rock', 'Pop']
489
vapnet: ['Non-Music', "Children's"]
490
laleh: ['Jazz', 'Rock', 'Latin', 'Pop']
491
markus krunegård: ['Rock']
492
kooks the: ['Rock']
493
deportees: ['Reggae']
494
r.e.m: ['Rock']
495
Artista não encontrado: slagsmalklubben
slagsmalklubben: []
496
hot chip: ['Electronic']
497
millencolin: ['Rock']
498
the sounds: ['Electronic']
499
mew: ['Rock']
500
!green day: ['Rock']
501
kings of convenience: ['Rock', 'Pop']
502
firefox ak: ['Electronic']
503
mando diao: ['Rock', 'Pop']
504
the tough alliance: ['Electronic', 'Rock', 'Pop']
505
shout out louds: ['Rock', 'Pop']
506
keane: ['Rock', 'Pop']
507
wir sind helden: ['Rock', 'Pop']
508
thompson twins: ['Pop']
509
hanson: ['Electronic']
510
no doubt: ['Rock']
511
Artista não encontrado: orchestral man˛vres in the dark
orchestral man˛vres in the dark: []
512
human league: ['Electronic']
513
altered images: ['Electronic', 'Rock']
514
martina mcbride: ['Folk, World, & Country']
515
yazoo: ['Electronic', 'Pop']
516
regina spector: ['Latin', 'Pop']
517
the format: ['Hip Hop']
518
carolyn dawn johnson: ['Rock']
519
mazzy star: ['Rock']
520
Artista não encontrado: dashboard confesssional
dashboard confesssional: []
521
larson, jonathan: ['Stage & Screen']
522
wicked: ['Electronic']
523
the verve pipe: ['Rock']
524
missing persons: ['Electronic', 'Rock']
525
the passions: ['Jazz']
526
ima robot.: ['Rock']
527
holofernes, judith: ['Rock', 'Pop']
528
delpech mode: ['Electronic', 'Pop']
529
fake: ['Electronic', 'Funk / Soul']
530
der plan: ['Electronic']
531
gwen stefani: ['Non-Music']
532
dierks bentley: ['Folk, World, & Country']
533
heaven 17: ['Electronic', 'Rock']
534
the sundays: ['Rock']
535
dixie chicks: ['Pop', 'Folk, World, & Country']
536
shania t wain: ['Electronic', 'Rock']
537
stacey q: ['Electronic', 'Pop']
538
camera obscura: ['Electronic', 'Rock']
539
deana carter: ['Folk, World, & Country']
540
Artista não encontrado: mattandkim
mattandkim: []
541
steel train: ['Rock']
542
dan_fogelberg: ['Rock']
543
taking back sunday: ['Rock']
544
andrew bird: ['Rock']
545
jewel: ['Rock']
546
britney　spears: ['Electronic', 'Hip Hop', 'Funk / Soul', 'Pop']
547
kristy lee: ['Electronic', 'Hip Hop']
548
sting & the police: ['Rock']
549
the portal service: ['Electronic', 'Rock']
550
fefe dobson: ['Rock', 'Pop']
551
julie roberts: ['Folk, World, & Country']
552
j dilla: ['Hip Hop']
553
nas: ['Hip Hop']
554
common: ['Electronic']
555
black milk: ['Rock']
556
pete rock: ['Hip Hop']
557
jay z: ['Hip Hop']
558
dr dre: ['Hip Hop']
559
evidence: ['Electronic']
560
 kanye west: ['Hip Hop', 'Classical']
561
dpz: ['Electronic']
562
percee p: ['Hip Hop']
563
jeff mills: ['Electronic']
564
method man: ['Hip Hop']
565

KeyboardInterrupt:

Salvando json em disco

In [35]:
with open(json_path, 'w') as fp:
    json.dump(artists_genres, fp)

----------------------------------------------

## Netflix Prize

In [19]:
column_names = ['MovieID', 'YearOfRelease', 'Title']
movie_titles = pd.read_csv('../Datasets/Netflix/movie_titles.csv', 
                           encoding='ISO-8859-1', 
                           header=None,
                           names=column_names,
                           on_bad_lines ='skip')

In [20]:
movie_titles

,MovieID,YearOfRelease,Title
0,1,2003.0,Dinosaur Planet
1,2,2004.0,Isle of Man TT 2004 Review
2,3,1997.0,Character
3,4,1994.0,Paula Abdul's Get Up & Dance
4,5,2004.0,The Rise and Fall of ECW
...,...,...,...
17429,17766,2002.0,Where the Wild Things Are and Other Maurice Se...
17430,17767,2004.0,Fidel Castro: American Experience
17431,17768,2000.0,Epoch
17432,17769,2003.0,The Company
17433,17770,2003.0,Alien Hunter

In [21]:
print(functions.df_to_latex(movie_titles.head(), 'Primeiras 5 linhas do conjunto de dados Netflix Prize'))

\begin{table}[]
\centering
        \begin{tabular}{ccc}
\toprule
MovieID & YearOfRelease & Title \\
\midrule
1 & 2003.000000 & Dinosaur Planet \\
2 & 2004.000000 & Isle of Man TT 2004 Review \\
3 & 1997.000000 & Character \\
4 & 1994.000000 & Paula Abdul's Get Up & Dance \\
5 & 2004.000000 & The Rise and Fall of ECW \\
\bottomrule
\end{tabular}

\caption{Primeiras 5 linhas do conjunto de dados Netflix Prize}
\end{table}

In [14]:
# FONTE: https://www.kaggle.com/code/nityaverma19/user-based-cf

def read_combined_data(file_path):
    # Initialize lists to store data
    movie_ids = []
    customer_ids = []
    ratings = []
    dates = []

    # Read the file
    with open(file_path, 'r') as file:
        lines = file.readlines()

    # Initialize variables
    current_movie_id = None

    # Process each line
    for line in lines:
        # Strip leading/trailing whitespaces
        line = line.strip()

        # Check for movie ID
        if line.endswith(':'):
            # Update current movie ID
            current_movie_id = line[:-1].strip()
        elif line:  # Check if the line is not empty
            # Extract customer data
            data = line.strip().split(',')
            if len(data) >= 3:
                customer_id = data[0].strip()
                rating_str = data[1].strip()
                date = data[2].strip()

                try:
                    rating = float(rating_str)
                except ValueError:
                    print(f"Skipping invalid rating (not a valid float): '{rating_str}'")
                    continue

                # Append data to lists
                movie_ids.append(current_movie_id)
                customer_ids.append(customer_id)
                ratings.append(rating)
                dates.append(date)
            else:
                print(f"Skipping line with insufficient data: '{line}'")

    # Create DataFrame
    combined_data = pd.DataFrame({
        'MovieID': movie_ids,
        'CustomerID': customer_ids,
        'Rating': ratings,
        'Date': dates
    })

    return combined_data

# Read combined_data_1.txt
file_path = '../Datasets/Netflix/combined_data_1.txt'
print(f"Reading file: {file_path}")
data_1 = read_combined_data(file_path)

# Display the first few rows of the DataFrame
print(data_1.head())

Reading file: ../Datasets/Netflix/combined_data_1.txt
  MovieID CustomerID  Rating        Date
0       1    1488844     3.0  2005-09-06
1       1     822109     5.0  2005-05-13
2       1     885013     4.0  2005-10-19
3       1      30878     4.0  2005-12-26
4       1     823519     3.0  2004-05-03

In [15]:
data_1

         MovieID CustomerID  Rating        Date
0              1    1488844     3.0  2005-09-06
1              1     822109     5.0  2005-05-13
2              1     885013     4.0  2005-10-19
3              1      30878     4.0  2005-12-26
4              1     823519     3.0  2004-05-03
...          ...        ...     ...         ...
24053759    4499    2591364     2.0  2005-02-16
24053760    4499    1791000     2.0  2005-02-10
24053761    4499     512536     5.0  2005-07-27
24053762    4499     988963     3.0  2005-12-20
24053763    4499    1704416     3.0  2004-06-02

[24053764 rows x 4 columns]

In [16]:
print(functions.df_to_latex(data_1.head(), 'Primeiras 5 linhas do conjunto de dados Netflix Prize'))

\begin{table}[]
\centering
        \begin{tabular}{cccc}
\toprule
MovieID & CustomerID & Rating & Date \\
\midrule
1 & 1488844 & 3.000000 & 2005-09-06 \\
1 & 822109 & 5.000000 & 2005-05-13 \\
1 & 885013 & 4.000000 & 2005-10-19 \\
1 & 30878 & 4.000000 & 2005-12-26 \\
1 & 823519 & 3.000000 & 2004-05-03 \\
\bottomrule
\end{tabular}

\caption{Primeiras 5 linhas do conjunto de dados Netflix Prize}
\end{table}

## MovieLens

In [3]:
df = pd.read_csv('../Datasets/MovieLens/100K/ml-100k/u.data',
                names=['userId', 'itemId', 'rating', 'timestamp'],
                sep='\t')

In [5]:
df = df[['userId', 'itemId', 'rating']]

In [7]:
print(functions.df_to_latex(df.head(), 'Primeiras 5 linhas do conjunto de dados MovieLens 20M'))

\begin{table}[]
\centering
        \begin{tabular}{ccc}
\toprule
userId & itemId & rating \\
\midrule
196 & 242 & 3 \\
186 & 302 & 3 \\
22 & 377 & 1 \\
244 & 51 & 2 \\
166 & 346 & 1 \\
\bottomrule
\end{tabular}

\caption{Primeiras 5 linhas do conjunto de dados MovieLens 20M}
\end{table}

In [13]:
df = pd.read_csv('../Datasets/MovieLens/100K/ml-100k/u.item',
                 usecols=range(11),
                 names = ['movieId', 
                       'movieTitle', 
                       'releaseDate', 
                       'videoReleaseDate', 
                       'imdbURL', 
                       'unknow', 
                       'action', 
                       'adventure', 
                       'animation',
                       'Children',
                       'documentary'],
                sep='|',
                encoding='iso-8859-1')

In [15]:
df = df[['movieId', 'movieTitle', 'action', 'adventure', 'animation']]

In [17]:
df['...'] = '...'

/tmp/ipykernel_3575/218817001.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['...'] = '...'

In [19]:
print(functions.df_to_latex(df.head(), 'Primeiras 5 linhas do conjunto de descrições de itens do MovieLens 20M'))

\begin{table}[]
\centering
        \begin{tabular}{cccccc}
\toprule
movieId & movieTitle & action & adventure & animation & ... \\
\midrule
1 & Toy Story (1995) & 0 & 0 & 1 & ... \\
2 & GoldenEye (1995) & 1 & 1 & 0 & ... \\
3 & Four Rooms (1995) & 0 & 0 & 0 & ... \\
4 & Get Shorty (1995) & 1 & 0 & 0 & ... \\
5 & Copycat (1995) & 0 & 0 & 0 & ... \\
\bottomrule
\end{tabular}

\caption{Primeiras 5 linhas do conjunto de descrições de itens do MovieLens 20M}
\end{table}

# Exemplo de utility matrix

In [4]:
data = [['usuario1', 2, '-', 5, '-'], ['usuario2', '-', 1 , '-', 4], ['usuario3', 3, 1, '-', 2], ['usuario4', '-', 2, '-', 5]]

In [5]:
df_ex = pd.DataFrame(data, columns=['Usuarios', 'Item 1', 'Item 2', 'Item 3', 'Item 4'])

In [7]:
print(functions.df_to_latex(df_ex, 'Exemplo de matriz de utilidade'))

\begin{table}[]
\centering
        \begin{tabular}{ccccc}
\toprule
Usuarios & Item 1 & Item 2 & Item 3 & Item 4 \\
\midrule
usuario1 &      2 &      - &      5 &      - \\
usuario2 &      - &      1 &      - &      4 \\
usuario3 &      3 &      1 &      - &      2 \\
usuario4 &      - &      2 &      - &      5 \\
\bottomrule
\end{tabular}

\caption{Exemplo de matriz de utilidade}
\end{table}

C:\Users\David\Documents\UFABC\PGC\Codigos\functions.py:5: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  latex = latex + df.to_latex(index=False, header=True,

In [5]:
print(df_ex.to_latex(index=False, header=True, column_format='ccccc'))

\begin{tabular}{ccccc}
\toprule
Usuarios & Item 1 & Item 2 & Item 3 & Item 4 \\
\midrule
usuario1 &      3 &      - &      2 &      - \\
usuario2 &      - &      4 &      - &      2 \\
usuario3 &      4 &      - &      3 &      - \\
usuario4 &      - &      5 &      4 &      1 \\
\bottomrule
\end{tabular}

C:\Users\David\AppData\Local\Temp\ipykernel_15908\372530190.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(df_ex.to_latex(index=False, header=True, column_format='ccccc'))

In [9]:
user,item,title = 'userId','movieId','title'

In [12]:
df = pd.read_csv('../Datasets/MovieLens/100K/ml-100k/u.data', sep='\t', header=None, names=[user,item,'rating','timestamp'])[[user,item,'rating']]

In [23]:
df = df.sort_values(by=['userId', 'movieId'])

In [24]:
print(functions.df_to_latex(df.head(), 'Exemplo de matriz de utilidade'))

\begin{table}[]
\centering
        \begin{tabular}{ccc}
\toprule
 userId &  movieId &  rating \\
\midrule
      1 &        1 &       5 \\
      1 &        2 &       3 \\
      1 &        3 &       4 \\
      1 &        4 &       3 \\
      1 &        5 &       3 \\
\bottomrule
\end{tabular}

\caption{Exemplo de matriz de utilidade}
\end{table}

C:\Users\David\Documents\UFABC\PGC\Codigos\functions.py:5: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  latex = latex + df.to_latex(index=False, header=True,

In [3]:
df = pd.read_csv('./Datasets/movie_titles.csv', encoding = 'ANSI', sep=',', usecols=range(3), lineterminator='\n', names=['movieId', 'year', 'title'])

In [ ]:
df

In [8]:
df2 = pd.read_csv('../Datasets/Netflix/netflix_genres.csv')

In [9]:
df2

       movieId                            genres
0            1      Documentary|Animation|Family
1            3               Crime|Drama|Mystery
2            4                            Family
3            5                 Documentary|Sport
4            6                       Documentary
...        ...                               ...
12274    17764      Comedy|Drama|History|Romance
12275    17765    Action|Adventure|Family|Sci-Fi
12276    17768              Action|Drama|Fantasy
12277    17769               Drama|Music|Romance
12278    17770  Action|Adventure|Sci-Fi|Thriller

[12279 rows x 2 columns]

In [ ]:
df_merge = pd.merge(df, df2, how='left')

In [ ]:
df_merge

In [ ]:
df_merge = df_merge[~df_merge['genres'].isna()]

In [ ]:
df_merge['genres'] = df_merge['genres'].astype(str)

In [ ]:
df_merge['n_bars'] = df_merge['genres'].str.count(r'[|]')

In [ ]:
df_merge[df_merge['n_bars'] > 9]

In [ ]:
df_merge[['genre1', 'genre2', 'genre3', 'genre4']] =

# LastFm

In [ ]:
df = pd.read_csv()